---
duel_sith_temple_singleplayer:
  guid: 210
  max_players: 1
  template_name: 10831
  asset_name: LD_DarthMaul
  hide_ui: false
  is_combat: false
  default_point_of_interest:
    guid: 210
    pos:
      x: 376.8
      y: 102
      z: 299.1
      w: 1
    rot:
      x: 0
      y: 0
      z: 0
      w: 0
  speed: 0
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
