---
duel_dathomir_arena_day_singleplayer:
  guid: 208
  max_players: 1
  template_name: 52203
  asset_name: LD_Dathomir_Arena_Day
  hide_ui: false
  is_combat: false
  default_point_of_interest:
    guid: 208
    pos:
      x: 306
      y: 100
      z: 300
      w: 1
    rot:
      x: 0
      y: 0
      z: 0
      w: 0
  spawn_sky: Sky_LD_Dathomir_Day.xml
  speed: 0
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
