---
# Blue
- guid: 130000
  name_id: 2527
  description_id: 14
  icon_set_id: 398
  tint: 20
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Green
- guid: 130001
  name_id: 2528
  description_id: 14
  icon_set_id: 399
  tint: 21
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Yellow
- guid: 130002
  name_id: 2529
  description_id: 14
  icon_set_id: 408
  tint: 22
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Orange
- guid: 130003
  name_id: 2530
  description_id: 14
  icon_set_id: 401
  tint: 23
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Red
- guid: 130004
  name_id: 2531
  description_id: 14
  icon_set_id: 404
  tint: 24
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Purple
- guid: 130005
  name_id: 2532
  description_id: 14
  icon_set_id: 403
  tint: 25
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Silver
- guid: 130006
  name_id: 2533
  description_id: 14
  icon_set_id: 405
  tint: 26
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Teal
- guid: 130007
  name_id: 2534
  description_id: 14
  icon_set_id: 406
  tint: 27
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Pink
- guid: 130008
  name_id: 2535
  description_id: 14
  icon_set_id: 402
  tint: 28
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Light Green
- guid: 130009
  name_id: 2536
  description_id: 14
  icon_set_id: 400
  tint: 29
  slot: !Equipment SecondarySaberColor
  item_type: 1
# White
- guid: 130010
  name_id: 2537
  description_id: 14
  icon_set_id: 407
  tint: 30
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Black
- guid: 130011
  name_id: 2538
  description_id: 14
  icon_set_id: 397
  tint: 31
  slot: !Equipment SecondarySaberColor
  item_type: 1
# Sith Crystal
- guid: 130012
  name_id: 51152
  description_id: 14
  icon_set_id: 2772
  tint: 47
  slot: !Equipment SecondarySaberColor
  item_type: 1
