---
# Aayla Secura's Lightsaber
- guid: 140010
  name_id: 306
  description_id: 14
  icon_set_id: 221
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_AaylaSecura.adr
  texture_alias: AaylaSecura
  item_type: 25
# Adi Gallia's Lightsaber
- guid: 140011
  name_id: 8768
  description_id: 14
  icon_set_id: 222
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_AdiGallia.adr
  texture_alias: AdiGallia
  item_type: 25
  members: true
# 'Umbara Academy: Ghost Attack 1'
- guid: 140013
  name_id: 51036
  description_id: 14
  icon_set_id: 425
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_AhsokaV2_Ghost.adr
  texture_alias: Ahsoka
  item_type: 25
# Ahsoka Tano's Offhand Lightsaber
- guid: 140014
  name_id: 19893
  description_id: 14
  icon_set_id: 1459
  item_class: 10
  slot: !Equipment SecondaryWeapon
  model_name: Wield_LightsaberHiltStandard_AhsokaV2_LEFT.adr
  texture_alias: Ahsoka
  item_type: 25
  category: 64
# Anakin Skywalker's Lightsaber
- guid: 140015
  name_id: 8762
  description_id: 14
  icon_set_id: 223
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Anakin.adr
  texture_alias: Anakin
  item_type: 25
# 'Umbara Academy: Ghost Attack 2'
- guid: 140016
  name_id: 51037
  description_id: 14
  icon_set_id: 425
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Anakin_Ghost.adr
  texture_alias: Anakin
  item_type: 25
# Barriss Offee's Lightsaber
- guid: 140017
  name_id: 14786
  description_id: 14
  icon_set_id: 508
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_BarrissOffee.adr
  texture_alias: BarrissOffee
  item_type: 25
  members: true
# Byph's Lightsaber
- guid: 140018
  name_id: 53615
  description_id: 14
  icon_set_id: 3207
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Byph.adr
  texture_alias: Byph
  item_type: 25
  members: true
# Miko Jedi Lightsaber
- guid: 140019
  name_id: 14788
  description_id: 14
  icon_set_id: 509
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_CompressedCrystal.adr
  texture_alias: CompressedCrystal
  item_type: 25
# Sith Infiltrator Lightsaber
- guid: 140020
  name_id: 4976
  description_id: 14
  icon_set_id: 3045
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_DarkForcePhaseI.adr
  texture_alias: DarkForcePhaseI
  item_type: 25
# Pre Vizsla's Darksaber
- guid: 140021
  name_id: 8763
  description_id: 14
  icon_set_id: 224
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Darksaber.adr
  texture_alias: PreVizsla
  item_type: 25
# Dolovite Darksaber
- guid: 140022
  name_id: 54592
  description_id: 14
  icon_set_id: 3829
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Darksaber.adr
  texture_alias: Gold
  item_type: 25
# Phrik Darksaber
- guid: 140023
  name_id: 54521
  description_id: 14
  icon_set_id: 3791
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Darksaber_Ancient.adr
  texture_alias: PreVizsla
  item_type: 25
# Darth Maul's Lightsaber
- guid: 140024
  name_id: 4718
  description_id: 14
  icon_set_id: 2764
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_DarthMaul.adr
  texture_alias: Maul
  item_type: 25
  members: true
# Count Dooku's Lightsaber
- guid: 140025
  name_id: 8766
  description_id: 14
  icon_set_id: 225
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Dooku.adr
  texture_alias: Dooku
  item_type: 25
# Eeth Koth's Lightsaber
- guid: 140026
  name_id: 2440
  description_id: 14
  icon_set_id: 226
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_EethKoth.adr
  texture_alias: EethKoth
  item_type: 25
# Jedi Exile Lightsaber
- guid: 140027
  name_id: 54602
  description_id: 14
  icon_set_id: 3835
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Exile.adr
  texture_alias: Exile
  item_type: 25
# Forked Lightsaber
- guid: 140028
  name_id: 54593
  description_id: 14
  icon_set_id: 3828
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Forked.adr
  texture_alias: Forked
  item_type: 25
# Ganodi's Lightsaber
- guid: 140029
  name_id: 53620
  description_id: 14
  icon_set_id: 3212
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Ganodi.adr
  texture_alias: Ganodi
  item_type: 25
  members: true
# Ultimate FX Gungan Lightsaber
- guid: 140030
  name_id: 2650
  description_id: 14
  icon_set_id: 2136
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Gungan.adr
  texture_alias: Gungan
  item_type: 25
# Gungi's Lightsaber
- guid: 140031
  name_id: 53616
  description_id: 14
  icon_set_id: 3208
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Gungi.adr
  texture_alias: Gundi
  item_type: 25
  members: true
# Jocasta Nu's Lightsaber
- guid: 140032
  name_id: 8769
  description_id: 14
  icon_set_id: 227
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Jocasta.adr
  texture_alias: Jocasta
  item_type: 25
  members: true
# Kashyyyk Lightsaber
- guid: 140033
  name_id: 44507
  description_id: 14
  icon_set_id: 1993
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Kashyyk.adr
  texture_alias: Kashyyk
  item_type: 25
  members: true
# Mestare Lightsaber
- guid: 140034
  name_id: 44850
  description_id: 14
  icon_set_id: 510
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Katana.adr
  texture_alias: SamuraiJedi
  item_type: 25
# Katooni's Lightsaber
- guid: 140035
  name_id: 53621
  description_id: 14
  icon_set_id: 3213
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Katooni.adr
  texture_alias: Katooni
  item_type: 25
  members: true
# Ki-Adi-Mundi's Lightsaber
- guid: 140036
  name_id: 2444
  description_id: 14
  icon_set_id: 228
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_KiAdiMundi.adr
  texture_alias: KiAdiMundi
  item_type: 25
# Kit Fisto's Lightsaber
- guid: 140037
  name_id: 8767
  description_id: 14
  icon_set_id: 229
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_KitFisto.adr
  texture_alias: KitFisto
  item_type: 25
# Kyle Katarn's Lightsaber
- guid: 140038
  name_id: 974
  description_id: 14
  icon_set_id: 511
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_KyleKatarn.adr
  texture_alias: KyleKatarn
  item_type: 25
# Sulon Jedi Lightsaber
- guid: 140039
  name_id: 60157
  description_id: 14
  icon_set_id: 511
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_KyleKatarn.adr
  texture_alias: KyleKatarn
  item_type: 25
# Luke Skywalker's Lightsaber
- guid: 140040
  name_id: 8770
  description_id: 14
  icon_set_id: 230
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_LukeSkywalker.adr
  texture_alias: LukeSkywalker
  item_type: 25
# Luminara Unduli's Lightsaber
- guid: 140041
  name_id: 8771
  description_id: 14
  icon_set_id: 231
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Luminara.adr
  texture_alias: Luminara
  item_type: 25
  members: true
# Plo Koon's Lightsaber
- guid: 140042
  name_id: 308
  description_id: 14
  icon_set_id: 232
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Luminara.adr
  texture_alias: PloKoon
  item_type: 25
  members: true
# Mace Windu's Lightsaber
- guid: 140043
  name_id: 8772
  description_id: 14
  icon_set_id: 233
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_MaceWindu.adr
  texture_alias: MaceWindu
  item_type: 25
# 'Umbara Academy: Ghost Attack 3'
- guid: 140044
  name_id: 51038
  description_id: 14
  icon_set_id: 425
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_MaceWindu_Ghost.adr
  texture_alias: MaceWindu
  item_type: 25
# Obi-Wan Kenobi's Lightsaber
- guid: 140045
  name_id: 8773
  description_id: 14
  icon_set_id: 234
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_ObiWan.adr
  texture_alias: ObiWan
  item_type: 25
  members: true
# Petro's Lightsaber
- guid: 140046
  name_id: 53617
  description_id: 14
  icon_set_id: 3209
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Petro.adr
  texture_alias: Petro
  item_type: 25
  members: true
# Shotem Jedi Lightsaber
- guid: 140047
  name_id: 976
  description_id: 14
  icon_set_id: 512
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Pulsating.adr
  texture_alias: PulsatingCrystal
  item_type: 25
# Shotem Master Lightsaber
- guid: 140048
  name_id: 60678
  description_id: 14
  icon_set_id: 3788
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Pulsating.adr
  texture_alias: PulsingCrystalBlue
  item_type: 25
# Quinlan Vos' Lightsaber
- guid: 140049
  name_id: 19637
  description_id: 14
  icon_set_id: 1436
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_QuinlanVos.adr
  texture_alias: QuinlanVos
  item_type: 25
# Saesee Tiin's Lightsaber
- guid: 140050
  name_id: 43190
  description_id: 14
  icon_set_id: 1792
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_SaeseeTiin.adr
  texture_alias: SaeseeTiin
  item_type: 25
# Shaak Ti's Lightsaber
- guid: 140051
  name_id: 14792
  description_id: 14
  icon_set_id: 513
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_ShaakTi.adr
  texture_alias: ShaakTi
  item_type: 25
  members: true
# Darth Sidious' Lightsaber
- guid: 140052
  name_id: 8774
  description_id: 14
  icon_set_id: 235
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Sidious.adr
  texture_alias: Sidious
  item_type: 25
# Bravis Sith Lightsaber
- guid: 140053
  name_id: 978
  description_id: 14
  icon_set_id: 514
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_SparkingCrystal.adr
  texture_alias: SparkingCrystal
  item_type: 25
  members: true
# Crimson Prowler Lightsaber
- guid: 140054
  name_id: 60198
  description_id: 14
  icon_set_id: 3721
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_SparkingCrystal.adr
  texture_alias: DarkKnight
  item_type: 25
# Ermi Jedi Lightsaber
- guid: 140055
  name_id: 980
  description_id: 14
  icon_set_id: 515
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Spiraling.adr
  texture_alias: Spiraling
  item_type: 25
  members: true
# Talz Lightsaber
- guid: 140056
  name_id: 4824
  description_id: 14
  icon_set_id: 2863
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Talz.adr
  texture_alias: Talz
  item_type: 25
# Training Lightsaber
- guid: 140057
  name_id: 8775
  description_id: 14
  icon_set_id: 236
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Training.adr
  texture_alias: Padawan1
  item_type: 25
# Ancient Cobal Lightsaber
- guid: 140058
  name_id: 982
  description_id: 14
  icon_set_id: 516
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Training.adr
  texture_alias: BuggyCrystal
  item_type: 25
# Savek Lightsaber
- guid: 140059
  name_id: 14794
  description_id: 14
  icon_set_id: 517
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Unstable.adr
  texture_alias: Unstable
  item_type: 25
  members: true
# Asajj Ventress' Left Lightsaber
- guid: 140061
  name_id: 8776
  description_id: 14
  icon_set_id: 237
  item_class: 10
  slot: !Equipment SecondaryWeapon
  model_name: Wield_LightsaberHiltStandard_Ventress_LEFT.adr
  texture_alias: Ventress
  item_type: 25
  category: 64
  members: true
# Yoda's Lightsaber
- guid: 140062
  name_id: 1797
  description_id: 14
  icon_set_id: 3169
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Yoda.adr
  texture_alias: Yoda
  item_type: 25
# Zatt's Lightsaber
- guid: 140063
  name_id: 53619
  description_id: 14
  icon_set_id: 3211
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Zatt.adr
  texture_alias: Zatt
  item_type: 25
  members: true
# Dahgee Jedi Lightsaber
- guid: 140064
  name_id: 986
  description_id: 14
  icon_set_id: 1148
  item_class: 10
  slot: !Equipment None
  model_name: Wield_LightsaberHiltStandard_Zebra.adr
  texture_alias: ZebraStripes
  item_type: 25
  members: true
