---
ryloth:
  ambient_npcs:
    holotable_holograms:
      name_id: 32914
      model_id: 44
      pos:
        x: 593.89545
        y: 10
        z: 672.5175
        w: 1
      rot:
        x: 0
        y: 0
        z: 0
        w: 0
      cursor: 54
      show_name: false
      interact_radius: 3.3
      move_to_interact_offset: 3.2
      tickable_procedures:
        arc_troopers_hologram:
          steps:
            - model_id: 354
              min_duration_millis: 10000
          next_possible_procedures:
            - procedure: invisible
        battle_droid_hologram:
          steps:
            - model_id: 352
              min_duration_millis: 10000
          next_possible_procedures:
            - procedure: invisible
        super_battle_droid_hologram:
          steps:
            - model_id: 351
              min_duration_millis: 10000
          next_possible_procedures:
            - procedure: invisible
        droideka_hologram:
          steps:
            - animation_id: 9002
              model_id: 350
              min_duration_millis: 10000
          next_possible_procedures:
            - procedure: invisible
        invisible:
          steps:
            - model_id: 44
              min_duration_millis: 5000
          next_possible_procedures:
            - procedure: arc_troopers_hologram
            - procedure: battle_droid_hologram
            - procedure: super_battle_droid_hologram
            - procedure: droideka_hologram
      one_shot_interaction:
        script: OpenGalaxyMap
        duration_millis: 1
    fighter:
      name_id: 32914
      terrain_object_id: 1332791341
      pos:
        x: 555.7068
        y: 10.99902
        z: 649.7574
        w: 1
      rot:
        x: 0
        y: 0
        z: 0
        w: 0
      name_offset_x: -0.5
      cursor: 0
      show_name: false
      notification_icon: 37
      hover_description: UseName
      one_shot_interaction:
        script: OpenGalaxyMap
        duration_millis: 1
