---
felucia:
  guid: 15
  max_players: 4294967295
  template_name: 52276
  asset_name: Combat_Felucia_01
  hide_ui: false
  is_combat: true
  default_point_of_interest:
    guid: 36
    pos:
      x: 488
      y: 0.9538704
      z: 278
      w: 1
    rot:
      x: 0
      y: 0
      z: 1
      w: 0
    name_id: 50654
  speed: 8
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
  map_id: 128
