[package]
name = "cwa-server"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
packet_serialize = { path = "src/packet_serialize" }
miniz_oxide = "0.7.2"
num_enum = "0.7.2"
parking_lot = "0.12.1"
rand = "0.8.5"
serde_json = "1.0.1"
serde = { version = "1.0.196", features = ["derive"] }
