---
members_only:
  ambient_npcs:
    #
    # Lightsaber Construction Chamber
    #

    #
    # Members
    #
    max_rebo:
      model_id: 1014
      name_id: 4782
      show_name: false
      enable_gravity: false
      pos:
        x: 800.338
        y: 11.77
        z: 668.0857
        w: 1.0
      rot:
        x: -0.6742825
        y: 0
        z: 0.73847353
        w: 0
      stand_animation_id: 2579
    clone_guard_members_only_1:
      model_id: 1936
      pos:
        x: 762.14
        y: 10.028671
        z: 680.5
        w: 1
      rot:
        x: 1
        y: 0
        z: 0
        w: 0
      stand_animation_id: 2505
      cursor: 54
      enable_interact_popup: false
      one_shot_action_on_interact:
        one_shot_action_animation_id: 2506
        duration_millis: 1000
      interact_radius: 6
      auto_interact_radius: 5
    clone_guard_members_only_2:
      model_id: 1936
      pos:
        x: 762.14
        y: 10.036716
        z: 687.5
        w: 1
      rot:
        x: 1
        y: 0
        z: 0
        w: 0
      stand_animation_id: 2505
      cursor: 54
      enable_interact_popup: false
      one_shot_action_on_interact:
        one_shot_action_animation_id: 2506
        duration_millis: 1000
      interact_radius: 6
      auto_interact_radius: 5
    clone_guard_members_only_3:
      model_id: 1936
      pos:
        x: 800.0
        y: 10.040405
        z: 674.48
        w: 1
      rot:
        x: -0.5
        y: 0
        z: 0.75
        w: 0
      stand_animation_id: 2505
      cursor: 54
      enable_interact_popup: false
      one_shot_action_on_interact:
        one_shot_action_animation_id: 2506
        duration_millis: 1000
      interact_radius: 6
      auto_interact_radius: 5
    # Liftable Crate
    members_only_npc_1:
      model_id: 825
      pos:
        x: 816.7
        y: 10.04
        z: 694.30
        w: 1.0
      rot:
        x: 0
        y: 0
        z: 0
        w: 0
      stand_animation_id: 2301
      cursor: 54
      enable_interact_popup: false
      one_shot_action_on_interact:
        player_one_shot_animation_id: 3014
        one_shot_action_animation_id: 2302
        duration_millis: 1000
    # Members Only Table 1
    members_only_table_1:
      model_id: 1010
      pos:
        x: 768.0
        y: 10.026612
        z: 679.1
        w: 1
      rot:
        x: 0
        y: 0
        z: -1
        w: 0
    # Jedi at Table
    members_only_npc_2:
      model_id: 39
      enable_gravity: false
      pos:
        x: 768.0
        y: 10.026612
        z: 679.1
        w: 1
      rot:
        x: 0
        y: 0
        z: -1
        w: 0
      stand_animation_id: 2566
    # Jedi at Table
    members_only_npc_3:
      model_id: 40
      enable_gravity: false
      pos:
        x: 768.0
        y: 10.026612
        z: 679.1
        w: 1
      rot:
        x: 0
        y: 0
        z: -1
        w: 0
      stand_animation_id: 2567
