---
members_only:
  doors:
    construction_chamber_to_veranda:
      pos:
        x: 1489.03
        y: 70
        z: 887.65
        w: 1
      terrain_object_id: 1281994173
      destination_pos:
        x: 919.5898
        y: 178.51657
        z: 1546.969
        w: 1
      destination_rot:
        x: -1.5
        y: 0
        z: 0
        w: 0
      destination_zone: !Any
        template_guid: 24
      interact_radius: 7
    club_to_lounge:
      pos:
        x: 761.51
        y: 10
        z: 683.99
        w: 1
      terrain_object_id: 1281995677
      destination_pos:
        x: -106.5555
        y: 10
        z: 1250.071
        w: 1
      destination_rot:
        x: 0
        y: 0
        z: 1.5
        w: 0
      destination_zone: !Any
        template_guid: 24
      interact_radius: 7
