---
members_only:
  ambient_npcs:
    construction_chamber_to_veranda:
      pos:
        x: 1489.03
        y: 70
        z: 887.65
        w: 1
      terrain_object_id: 1281994173
      cursor: 55
      enable_interact_popup: false
      auto_interact_radius: 1.5
      interact_radius: 7
      one_shot_interaction:
        point_of_interest: 10016
        duration_millis: 1

    club_to_lounge:
      pos:
        x: 761.51
        y: 10
        z: 683.99
        w: 1
      terrain_object_id: 1281995677
      cursor: 55
      enable_interact_popup: false
      auto_interact_radius: 1.5
      interact_radius: 7
      one_shot_interaction:
        point_of_interest: 10017
        duration_millis: 1
