---
# Boost Points
- guid: 1337
  name_id: 0
  description_id: 0
  icon_set_id: 0
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: -1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Spin Boost
- guid: 2240
  name_id: 33536
  description_id: 33537
  icon_set_id: 1691
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 15
  item_class: -1
  required_battle_class: 0
  slot: !Equipment None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Holocron Boost
- guid: 2384
  name_id: 33818
  description_id: 33819
  icon_set_id: 1687
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 15
  item_class: -1
  required_battle_class: 0
  slot: !Equipment None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Trivia Boost
- guid: 2385
  name_id: 33820
  description_id: 33821
  icon_set_id: 1693
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 15
  item_class: -1
  required_battle_class: 0
  slot: !Equipment None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
