---
- guid: 6
  name_id: 0
  description_id: 14
  icon_set_id: 1756
  tint: 0
  cost: 0
  item_class: 0
  required_battle_class: 0
  slot: !Equipment None
  disable_trade: false
  disable_sale: false
  model_name: Furniture_BuildingSetGeneric_Door01.adr
  texture_alias: ''
  required_gender: 0
  item_type: 29
  category: 1000
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: -1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 0
  customization_slot: None
  customization_id: 0
- guid: 7
  name_id: 0
  description_id: 14
  icon_set_id: 0
  tint: 0
  cost: 0
  item_class: 0
  required_battle_class: 0
  slot: !Equipment None
  disable_trade: false
  disable_sale: false
  model_name: Furniture_BuildingSetGeneric_Wall01.adr
  texture_alias: ''
  required_gender: 0
  item_type: 29
  category: 1000
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1000
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 0
  customization_slot: None
  customization_id: 0
- guid: 8
  name_id: 0
  description_id: 14
  icon_set_id: 0
  tint: 0
  cost: 0
  item_class: 0
  required_battle_class: 0
  slot: !Equipment None
  disable_trade: false
  disable_sale: false
  model_name: Furniture_BuildingSetGeneric_Window01.adr
  texture_alias: ''
  required_gender: 0
  item_type: 29
  category: 1000
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: -1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 0
  customization_slot: None
  customization_id: 0
- guid: 9
  name_id: 0
  description_id: 14
  icon_set_id: 0
  tint: 0
  cost: 0
  item_class: 0
  required_battle_class: 0
  slot: !Equipment None
  disable_trade: false
  disable_sale: false
  model_name: Furniture_BuildingSetGeneric_Floor01.adr
  texture_alias: ''
  required_gender: 0
  item_type: 29
  category: 1000
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1000
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 0
  customization_slot: None
  customization_id: 0
- guid: 10
  name_id: 0
  description_id: 14
  icon_set_id: 0
  tint: 0
  cost: 0
  item_class: 0
  required_battle_class: 0
  slot: !Equipment None
  disable_trade: false
  disable_sale: false
  model_name: Furniture_BuildingSetGeneric_Ceiling01.adr
  texture_alias: ''
  required_gender: 0
  item_type: 29
  category: 1000
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1000
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 0
  customization_slot: None
  customization_id: 0
