---
duel_venator_hangar_singleplayer:
  guid: 206
  max_players: 1
  template_name: 33127
  asset_name: LD_ForcePowers_Tutorial
  hide_ui: false
  is_combat: false
  default_point_of_interest:
    guid: 206
    pos:
      x: 236.4784
      y: 25
      z: 249.7896
      w: 1
    rot:
      x: 0
      y: 0
      z: 0
      w: 0
  speed: 0
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
