---
- hilt_item_guid: 110000
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110001
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110002
  shape_item_guid: 90000
  color_item_guid: 100009
- hilt_item_guid: 110003
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110004
  shape_item_guid: 90018
  color_item_guid: 100012
- hilt_item_guid: 110005
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110006
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110007
  shape_item_guid: 90006
  color_item_guid: 100006
- hilt_item_guid: 110008
  shape_item_guid: 90016
  color_item_guid: 100001
- hilt_item_guid: 110009
  shape_item_guid: 90001
  color_item_guid: 100010
- hilt_item_guid: 110010
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110011
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110012
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110013
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110015
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110016
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110017
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110018
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110019
  shape_item_guid: 90004
  color_item_guid: 100009
- hilt_item_guid: 110020
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110021
  shape_item_guid: 90001
  color_item_guid: 100010
- hilt_item_guid: 110022
  shape_item_guid: 90001
  color_item_guid: 100010
- hilt_item_guid: 110023
  shape_item_guid: 90002
  color_item_guid: 100001
- hilt_item_guid: 110024
  shape_item_guid: 90000
  color_item_guid: 100012
- hilt_item_guid: 110025
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110026
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110027
  shape_item_guid: 90000
  color_item_guid: 100002
- hilt_item_guid: 110028
  shape_item_guid: 90011
  color_item_guid: 100001
- hilt_item_guid: 110029
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110030
  shape_item_guid: 90012
  color_item_guid: 100005
- hilt_item_guid: 110031
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110032
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110033
  shape_item_guid: 90010
  color_item_guid: 100001
- hilt_item_guid: 110034
  shape_item_guid: 90013
  color_item_guid: 100006
- hilt_item_guid: 110035
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110036
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110037
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110038
  shape_item_guid: 90015
  color_item_guid: 100002
- hilt_item_guid: 110039
  shape_item_guid: 90015
  color_item_guid: 100000
- hilt_item_guid: 110040
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110041
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110042
  shape_item_guid: 90000
  color_item_guid: 100003
- hilt_item_guid: 110043
  shape_item_guid: 90000
  color_item_guid: 100005
- hilt_item_guid: 110044
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110045
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110046
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110047
  shape_item_guid: 90005
  color_item_guid: 100002
- hilt_item_guid: 110048
  shape_item_guid: 90005
  color_item_guid: 100000
- hilt_item_guid: 110049
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110050
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110051
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110052
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110053
  shape_item_guid: 90007
  color_item_guid: 100004
- hilt_item_guid: 110054
  shape_item_guid: 90007
  color_item_guid: 100012
- hilt_item_guid: 110055
  shape_item_guid: 90008
  color_item_guid: 100001
- hilt_item_guid: 110056
  shape_item_guid: 90009
  color_item_guid: 100007
- hilt_item_guid: 110057
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110058
  shape_item_guid: 90003
  color_item_guid: 100007
- hilt_item_guid: 110059
  shape_item_guid: 90009
  color_item_guid: 100004
- hilt_item_guid: 110060
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110062
  shape_item_guid: 90014
  color_item_guid: 100001
- hilt_item_guid: 110063
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110064
  shape_item_guid: 90019
  color_item_guid: 100001
- hilt_item_guid: 140010
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140011
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140013
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140014
  shape_item_guid: 120014
  color_item_guid: 130001
- hilt_item_guid: 140015
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140016
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140017
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140018
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140019
  shape_item_guid: 120004
  color_item_guid: 130009
- hilt_item_guid: 140020
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140021
  shape_item_guid: 120001
  color_item_guid: 130010
- hilt_item_guid: 140022
  shape_item_guid: 120001
  color_item_guid: 130010
- hilt_item_guid: 140023
  shape_item_guid: 120002
  color_item_guid: 130001
- hilt_item_guid: 140024
  shape_item_guid: 120000
  color_item_guid: 130012
- hilt_item_guid: 140025
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140026
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140027
  shape_item_guid: 120000
  color_item_guid: 130002
- hilt_item_guid: 140028
  shape_item_guid: 120011
  color_item_guid: 130001
- hilt_item_guid: 140029
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140030
  shape_item_guid: 120012
  color_item_guid: 130005
- hilt_item_guid: 140031
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140032
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140033
  shape_item_guid: 120010
  color_item_guid: 130001
- hilt_item_guid: 140034
  shape_item_guid: 120013
  color_item_guid: 130006
- hilt_item_guid: 140035
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140036
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140037
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140038
  shape_item_guid: 120015
  color_item_guid: 130002
- hilt_item_guid: 140039
  shape_item_guid: 120015
  color_item_guid: 130000
- hilt_item_guid: 140040
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140041
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140042
  shape_item_guid: 120000
  color_item_guid: 130003
- hilt_item_guid: 140043
  shape_item_guid: 120000
  color_item_guid: 130005
- hilt_item_guid: 140044
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140045
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140046
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140047
  shape_item_guid: 120005
  color_item_guid: 130002
- hilt_item_guid: 140048
  shape_item_guid: 120005
  color_item_guid: 130000
- hilt_item_guid: 140049
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140050
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140051
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140052
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140053
  shape_item_guid: 120007
  color_item_guid: 130004
- hilt_item_guid: 140054
  shape_item_guid: 120007
  color_item_guid: 130012
- hilt_item_guid: 140055
  shape_item_guid: 120008
  color_item_guid: 130001
- hilt_item_guid: 140056
  shape_item_guid: 120009
  color_item_guid: 130007
- hilt_item_guid: 140057
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140058
  shape_item_guid: 120003
  color_item_guid: 130007
- hilt_item_guid: 140059
  shape_item_guid: 120009
  color_item_guid: 130004
- hilt_item_guid: 140061
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140062
  shape_item_guid: 120014
  color_item_guid: 130001
- hilt_item_guid: 140063
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140064
  shape_item_guid: 120019
  color_item_guid: 130001
