---
# Primary Hilts
- guid: 3
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 0
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 110010
      unknown: 0
    - guid: 110011
      unknown: 0
    - guid: 110012
      unknown: 0
    - guid: 110005
      unknown: 0
    - guid: 110015
      unknown: 0
    - guid: 110058
      unknown: 0
    - guid: 110060
      unknown: 0
    - guid: 110017
      unknown: 0
    - guid: 110053
      unknown: 0
    - guid: 110018
      unknown: 0
    - guid: 110025
      unknown: 0
    - guid: 110054
      unknown: 0
    - guid: 110064
      unknown: 0
    - guid: 110024
      unknown: 0
    - guid: 110052
      unknown: 0
    - guid: 110022
      unknown: 0
    - guid: 110026
      unknown: 0
    - guid: 110055
      unknown: 0
    - guid: 110007
      unknown: 0
    - guid: 110028
      unknown: 0
    - guid: 110029
      unknown: 0
    - guid: 110031
      unknown: 0
    - guid: 110008
      unknown: 0
    - guid: 110027
      unknown: 0
    - guid: 110032
      unknown: 0
    - guid: 110033
      unknown: 0
    - guid: 110035
      unknown: 0
    - guid: 110036
      unknown: 0
    - guid: 110037
      unknown: 0
    - guid: 110009
      unknown: 0
    - guid: 110038
      unknown: 0
    - guid: 110040
      unknown: 0
    - guid: 110041
      unknown: 0
    - guid: 110043
      unknown: 0
    - guid: 110034
      unknown: 0
    - guid: 110019
      unknown: 0
    - guid: 110002
      unknown: 0
    - guid: 110045
      unknown: 0
    - guid: 110046
      unknown: 0
    - guid: 110023
      unknown: 0
    - guid: 110042
      unknown: 0
    - guid: 110021
      unknown: 0
    - guid: 110049
      unknown: 0
    - guid: 110050
      unknown: 0
    - guid: 110003
      unknown: 0
    - guid: 110059
      unknown: 0
    - guid: 110051
      unknown: 0
    - guid: 110047
      unknown: 0
    - guid: 110048
      unknown: 0
    - guid: 110020
      unknown: 0
    - guid: 110006
      unknown: 0
    - guid: 110000
      unknown: 0
    - guid: 110004
      unknown: 0
    - guid: 110039
      unknown: 0
    - guid: 110056
      unknown: 0
    - guid: 110057
      unknown: 0
    - guid: 110030
      unknown: 0
    - guid: 110013
      unknown: 0
    - guid: 110016
      unknown: 0
    - guid: 110044
      unknown: 0
    - guid: 110062
      unknown: 0
    - guid: 110001
      unknown: 0
    - guid: 110063
      unknown: 0
# Secondary Hilts
- guid: 8
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 0
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 140010
      unknown: 0
    - guid: 140011
      unknown: 0
    - guid: 140014
      unknown: 0
    - guid: 140015
      unknown: 0
    - guid: 140058
      unknown: 0
    - guid: 140061
      unknown: 0
    - guid: 140017
      unknown: 0
    - guid: 140053
      unknown: 0
    - guid: 140018
      unknown: 0
    - guid: 140025
      unknown: 0
    - guid: 140054
      unknown: 0
    - guid: 140064
      unknown: 0
    - guid: 140024
      unknown: 0
    - guid: 140052
      unknown: 0
    - guid: 140022
      unknown: 0
    - guid: 140026
      unknown: 0
    - guid: 140055
      unknown: 0
    - guid: 140028
      unknown: 0
    - guid: 140029
      unknown: 0
    - guid: 140031
      unknown: 0
    - guid: 140027
      unknown: 0
    - guid: 140032
      unknown: 0
    - guid: 140033
      unknown: 0
    - guid: 140035
      unknown: 0
    - guid: 140036
      unknown: 0
    - guid: 140037
      unknown: 0
    - guid: 140038
      unknown: 0
    - guid: 140040
      unknown: 0
    - guid: 140041
      unknown: 0
    - guid: 140043
      unknown: 0
    - guid: 140034
      unknown: 0
    - guid: 140019
      unknown: 0
    - guid: 140045
      unknown: 0
    - guid: 140046
      unknown: 0
    - guid: 140023
      unknown: 0
    - guid: 140042
      unknown: 0
    - guid: 140021
      unknown: 0
    - guid: 140049
      unknown: 0
    - guid: 140050
      unknown: 0
    - guid: 140059
      unknown: 0
    - guid: 140051
      unknown: 0
    - guid: 140047
      unknown: 0
    - guid: 140048
      unknown: 0
    - guid: 140020
      unknown: 0
    - guid: 140039
      unknown: 0
    - guid: 140056
      unknown: 0
    - guid: 140057
      unknown: 0
    - guid: 140030
      unknown: 0
    - guid: 140013
      unknown: 0
    - guid: 140016
      unknown: 0
    - guid: 140044
      unknown: 0
    - guid: 140062
      unknown: 0
    - guid: 140063
      unknown: 0
# Primary Colors
- guid: 4
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 0
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 100000
      unknown: 0
    - guid: 100001
      unknown: 0
    - guid: 100002
      unknown: 0
    - guid: 100003
      unknown: 0
    - guid: 100004
      unknown: 0
    - guid: 100005
      unknown: 0
    - guid: 100006
      unknown: 0
    - guid: 100007
      unknown: 0
    - guid: 100008
      unknown: 0
    - guid: 100009
      unknown: 0
    - guid: 100010
      unknown: 0
    - guid: 100011
      unknown: 0
    - guid: 100012
      unknown: 0
# Secondary Colors
- guid: 149
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 0
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 130000
      unknown: 0
    - guid: 130001
      unknown: 0
    - guid: 130002
      unknown: 0
    - guid: 130003
      unknown: 0
    - guid: 130004
      unknown: 0
    - guid: 130005
      unknown: 0
    - guid: 130006
      unknown: 0
    - guid: 130007
      unknown: 0
    - guid: 130008
      unknown: 0
    - guid: 130009
      unknown: 0
    - guid: 130010
      unknown: 0
    - guid: 130011
      unknown: 0
    - guid: 130012
      unknown: 0
# Primary Shapes
- guid: 5
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 0
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 90000
      unknown: 0
    - guid: 90001
      unknown: 0
    - guid: 90002
      unknown: 0
    - guid: 90003
      unknown: 0
    - guid: 90004
      unknown: 0
    - guid: 90005
      unknown: 0
    - guid: 90006
      unknown: 0
    - guid: 90007
      unknown: 0
    - guid: 90008
      unknown: 0
    - guid: 90009
      unknown: 0
    - guid: 90010
      unknown: 0
    - guid: 90011
      unknown: 0
    - guid: 90012
      unknown: 0
    - guid: 90013
      unknown: 0
    - guid: 90014
      unknown: 0
    - guid: 90015
      unknown: 0
    - guid: 90016
      unknown: 0
    - guid: 90017
      unknown: 0
    - guid: 90018
      unknown: 0
    - guid: 90019
      unknown: 0
# Secondary Shapes
- guid: 9
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 0
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 120000
      unknown: 0
    - guid: 120001
      unknown: 0
    - guid: 120002
      unknown: 0
    - guid: 120003
      unknown: 0
    - guid: 120004
      unknown: 0
    - guid: 120005
      unknown: 0
    - guid: 120006
      unknown: 0
    - guid: 120007
      unknown: 0
    - guid: 120008
      unknown: 0
    - guid: 120009
      unknown: 0
    - guid: 120010
      unknown: 0
    - guid: 120011
      unknown: 0
    - guid: 120012
      unknown: 0
    - guid: 120013
      unknown: 0
    - guid: 120014
      unknown: 0
    - guid: 120015
      unknown: 0
    - guid: 120016
      unknown: 0
    - guid: 120017
      unknown: 0
    - guid: 120018
      unknown: 0
    - guid: 120019
      unknown: 0
# Hair Style
- guid: 122
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 8
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 40118
      unknown: 0
    - guid: 40117
      unknown: 0
    - guid: 40116
      unknown: 0
    - guid: 40115
      unknown: 0
    - guid: 40114
      unknown: 0
    - guid: 40113
      unknown: 0
    - guid: 40112
      unknown: 0
    - guid: 40111
      unknown: 0
    - guid: 40110
      unknown: 0
    - guid: 40109
      unknown: 0
    - guid: 40108
      unknown: 0
    - guid: 40107
      unknown: 0
    - guid: 40106
      unknown: 0
    - guid: 40105
      unknown: 0
    - guid: 40104
      unknown: 0
    - guid: 40103
      unknown: 0
    - guid: 40102
      unknown: 0
    - guid: 40101
      unknown: 0
    - guid: 40100
      unknown: 0
    - guid: 40099
      unknown: 0
    - guid: 40098
      unknown: 0
    - guid: 40097
      unknown: 0
    - guid: 40096
      unknown: 0
    - guid: 40095
      unknown: 0
    - guid: 40094
      unknown: 0
    - guid: 40093
      unknown: 0
    - guid: 40092
      unknown: 0
    - guid: 40091
      unknown: 0
    - guid: 40090
      unknown: 0
    - guid: 40089
      unknown: 0
    - guid: 40088
      unknown: 0
    - guid: 40087
      unknown: 0
    - guid: 40086
      unknown: 0
    - guid: 40085
      unknown: 0
    - guid: 40084
      unknown: 0
    - guid: 40083
      unknown: 0
    - guid: 40082
      unknown: 0
    - guid: 40081
      unknown: 0
    - guid: 40080
      unknown: 0
    - guid: 40079
      unknown: 0
    - guid: 40078
      unknown: 0
    - guid: 40077
      unknown: 0
    - guid: 40076
      unknown: 0
    - guid: 40075
      unknown: 0
    - guid: 40074
      unknown: 0
    - guid: 40073
      unknown: 0
    - guid: 40072
      unknown: 0
    - guid: 40071
      unknown: 0
    - guid: 40070
      unknown: 0
    - guid: 40069
      unknown: 0
    - guid: 40068
      unknown: 0
    - guid: 40067
      unknown: 0
    - guid: 40066
      unknown: 0
    - guid: 40065
      unknown: 0
    - guid: 40064
      unknown: 0
    - guid: 40063
      unknown: 0
    - guid: 40062
      unknown: 0
    - guid: 40061
      unknown: 0
    - guid: 40060
      unknown: 0
    - guid: 40059
      unknown: 0
    - guid: 40058
      unknown: 0
    - guid: 40057
      unknown: 0
    - guid: 40056
      unknown: 0
    - guid: 40055
      unknown: 0
    - guid: 40054
      unknown: 0
    - guid: 40053
      unknown: 0
    - guid: 40052
      unknown: 0
    - guid: 40051
      unknown: 0
    - guid: 40050
      unknown: 0
    - guid: 40049
      unknown: 0
    - guid: 40048
      unknown: 0
    - guid: 40047
      unknown: 0
    - guid: 40046
      unknown: 0
    - guid: 40045
      unknown: 0
    - guid: 40044
      unknown: 0
    - guid: 40043
      unknown: 0
    - guid: 40042
      unknown: 0
    - guid: 40041
      unknown: 0
    - guid: 40040
      unknown: 0
    - guid: 40039
      unknown: 0
    - guid: 40038
      unknown: 0
    - guid: 40037
      unknown: 0
    - guid: 40036
      unknown: 0
    - guid: 40035
      unknown: 0
    - guid: 40034
      unknown: 0
    - guid: 40033
      unknown: 0
    - guid: 40032
      unknown: 0
    - guid: 40031
      unknown: 0
    - guid: 40030
      unknown: 0
    - guid: 40029
      unknown: 0
    - guid: 40028
      unknown: 0
    - guid: 40027
      unknown: 0
    - guid: 40026
      unknown: 0
    - guid: 40025
      unknown: 0
    - guid: 40024
      unknown: 0
    - guid: 40023
      unknown: 0
    - guid: 40022
      unknown: 0
    - guid: 40021
      unknown: 0
    - guid: 40020
      unknown: 0
    - guid: 40019
      unknown: 0
    - guid: 40018
      unknown: 0
    - guid: 40017
      unknown: 0
    - guid: 40016
      unknown: 0
    - guid: 40015
      unknown: 0
    - guid: 40014
      unknown: 0
    - guid: 40013
      unknown: 0
    - guid: 40012
      unknown: 0
    - guid: 40011
      unknown: 0
    - guid: 40010
      unknown: 0
    - guid: 40009
      unknown: 0
    - guid: 40008
      unknown: 0
    - guid: 40007
      unknown: 0
    - guid: 40006
      unknown: 0
    - guid: 40005
      unknown: 0
    - guid: 40004
      unknown: 0
    - guid: 40003
      unknown: 0
    - guid: 40002
      unknown: 0
    - guid: 40001
      unknown: 0
    - guid: 40000
      unknown: 0
# Hair Color
- guid: 123
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 8
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 30021
      unknown: 0
    - guid: 30020
      unknown: 0
    - guid: 30019
      unknown: 0
    - guid: 30018
      unknown: 0
    - guid: 30017
      unknown: 0
    - guid: 30016
      unknown: 0
    - guid: 30015
      unknown: 0
    - guid: 30014
      unknown: 0
    - guid: 30013
      unknown: 0
    - guid: 30012
      unknown: 0
    - guid: 30011
      unknown: 0
    - guid: 30010
      unknown: 0
    - guid: 30009
      unknown: 0
    - guid: 30008
      unknown: 0
    - guid: 30007
      unknown: 0
    - guid: 30006
      unknown: 0
    - guid: 30005
      unknown: 0
    - guid: 30004
      unknown: 0
    - guid: 30003
      unknown: 0
    - guid: 30002
      unknown: 0
    - guid: 30001
      unknown: 0
    - guid: 30000
      unknown: 0
# Eye Color
- guid: 124
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 8
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 10012
      unknown: 0
    - guid: 10011
      unknown: 0
    - guid: 10010
      unknown: 0
    - guid: 10009
      unknown: 0
    - guid: 10008
      unknown: 0
    - guid: 10007
      unknown: 0
    - guid: 10006
      unknown: 0
    - guid: 10005
      unknown: 0
    - guid: 10004
      unknown: 0
    - guid: 10003
      unknown: 0
    - guid: 10002
      unknown: 0
    - guid: 10001
      unknown: 0
    - guid: 10000
      unknown: 0
# Skin Tone
- guid: 125
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 8
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 60029
      unknown: 0
    - guid: 60028
      unknown: 0
    - guid: 60027
      unknown: 0
    - guid: 60026
      unknown: 0
    - guid: 60025
      unknown: 0
    - guid: 60024
      unknown: 0
    - guid: 60023
      unknown: 0
    - guid: 60022
      unknown: 0
    - guid: 60021
      unknown: 0
    - guid: 60020
      unknown: 0
    - guid: 60019
      unknown: 0
    - guid: 60018
      unknown: 0
    - guid: 60017
      unknown: 0
    - guid: 60016
      unknown: 0
    - guid: 60015
      unknown: 0
    - guid: 60014
      unknown: 0
    - guid: 60013
      unknown: 0
    - guid: 60012
      unknown: 0
    - guid: 60011
      unknown: 0
    - guid: 60010
      unknown: 0
    - guid: 60009
      unknown: 0
    - guid: 60008
      unknown: 0
    - guid: 60007
      unknown: 0
    - guid: 60006
      unknown: 0
    - guid: 60005
      unknown: 0
    - guid: 60004
      unknown: 0
    - guid: 60003
      unknown: 0
    - guid: 60002
      unknown: 0
    - guid: 60001
      unknown: 0
    - guid: 60000
      unknown: 0
# Face Design
- guid: 126
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 8
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 50062
      unknown: 0
    - guid: 50061
      unknown: 0
    - guid: 50060
      unknown: 0
    - guid: 50059
      unknown: 0
    - guid: 50058
      unknown: 0
    - guid: 50057
      unknown: 0
    - guid: 50056
      unknown: 0
    - guid: 50055
      unknown: 0
    - guid: 50054
      unknown: 0
    - guid: 50053
      unknown: 0
    - guid: 50052
      unknown: 0
    - guid: 50051
      unknown: 0
    - guid: 50050
      unknown: 0
    - guid: 50049
      unknown: 0
    - guid: 50048
      unknown: 0
    - guid: 50047
      unknown: 0
    - guid: 50046
      unknown: 0
    - guid: 50045
      unknown: 0
    - guid: 50044
      unknown: 0
    - guid: 50043
      unknown: 0
    - guid: 50042
      unknown: 0
    - guid: 50041
      unknown: 0
    - guid: 50040
      unknown: 0
    - guid: 50039
      unknown: 0
    - guid: 50038
      unknown: 0
    - guid: 50037
      unknown: 0
    - guid: 50036
      unknown: 0
    - guid: 50035
      unknown: 0
    - guid: 50034
      unknown: 0
    - guid: 50033
      unknown: 0
    - guid: 50032
      unknown: 0
    - guid: 50031
      unknown: 0
    - guid: 50030
      unknown: 0
    - guid: 50029
      unknown: 0
    - guid: 50028
      unknown: 0
    - guid: 50027
      unknown: 0
    - guid: 50026
      unknown: 0
    - guid: 50025
      unknown: 0
    - guid: 50024
      unknown: 0
    - guid: 50023
      unknown: 0
    - guid: 50022
      unknown: 0
    - guid: 50021
      unknown: 0
    - guid: 50020
      unknown: 0
    - guid: 50019
      unknown: 0
    - guid: 50018
      unknown: 0
    - guid: 50017
      unknown: 0
    - guid: 50016
      unknown: 0
    - guid: 50015
      unknown: 0
    - guid: 50014
      unknown: 0
    - guid: 50013
      unknown: 0
    - guid: 50012
      unknown: 0
    - guid: 50011
      unknown: 0
    - guid: 50010
      unknown: 0
    - guid: 50009
      unknown: 0
    - guid: 50008
      unknown: 0
    - guid: 50007
      unknown: 0
    - guid: 50006
      unknown: 0
    - guid: 50005
      unknown: 0
    - guid: 50004
      unknown: 0
    - guid: 50003
      unknown: 0
    - guid: 50002
      unknown: 0
    - guid: 50001
      unknown: 0
    - guid: 50000
      unknown: 0
# Facial Hair
- guid: 139
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 8
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 20014
      unknown: 0
    - guid: 20013
      unknown: 0
    - guid: 20012
      unknown: 0
    - guid: 20011
      unknown: 0
    - guid: 20010
      unknown: 0
    - guid: 20009
      unknown: 0
    - guid: 20008
      unknown: 0
    - guid: 20007
      unknown: 0
    - guid: 20006
      unknown: 0
    - guid: 20005
      unknown: 0
    - guid: 20004
      unknown: 0
    - guid: 20003
      unknown: 0
    - guid: 20002
      unknown: 0
    - guid: 20001
      unknown: 0
    - guid: 20000
      unknown: 0
# Species
- guid: 127
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 9
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 70012
      unknown: 0
    - guid: 70011
      unknown: 0
    - guid: 70010
      unknown: 0
    - guid: 70009
      unknown: 0
    - guid: 70008
      unknown: 0
    - guid: 70007
      unknown: 0
    - guid: 70006
      unknown: 0
    - guid: 70005
      unknown: 0
    - guid: 70004
      unknown: 0
    - guid: 70003
      unknown: 0
    - guid: 70002
      unknown: 0
    - guid: 70001
      unknown: 0
    - guid: 70000
      unknown: 0
# Boosts
- guid: 10000
  unknown2: 0
  name_id: 0
  description_id: 0
  sort_order: 0
  icon_set_id: 0
  category: 0
  page: 0
  unknown9: 0
  unknown10: 0
  unknown11: false
  unknown12: 0
  unknown13: 0
  unknown14: 0
  unknown16: ''
  unknown17: false
  items:
    - guid: 2240
      unknown: 0
    - guid: 2384
      unknown: 0
    - guid: 2385
      unknown: 0
