---
duel_hangar_singleplayer:
  guid: 204
  max_players: 1
  template_name: 13601
  asset_name: LD_QuinlanVos
  hide_ui: false
  is_combat: false
  default_point_of_interest:
    guid: 204
    pos:
      x: 246.5403
      y: 51
      z: 229.75
      w: 1
    rot:
      x: 0
      y: 0
      z: 0
      w: 0
  speed: 0
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
