---
# Lightsaber Beam Crystal
- guid: 90000
  name_id: 2526
  description_id: 14
  icon_set_id: 419
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_Basic.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Dark Beam Crystal
- guid: 90001
  name_id: 1258
  description_id: 14
  icon_set_id: 410
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_Darksaber.adr
  texture_alias: BlackSwirl
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Ancient Darksaber Crystal
- guid: 90002
  name_id: 54524
  description_id: 14
  icon_set_id: 410
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_Darksaber_Ancient.adr
  texture_alias: BlackSlick
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Cobal Crystal
- guid: 90003
  name_id: 1524
  description_id: 14
  icon_set_id: 396
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_FX_Basic_Buggy.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Compressed Beam Crystal
- guid: 90004
  name_id: 1253
  description_id: 14
  icon_set_id: 409
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_FX_Basic_Compressed.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Pulsing Beam Crystal
- guid: 90005
  name_id: 1254
  description_id: 14
  icon_set_id: 412
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_FX_Basic_Pulsing.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Radiating Ring Crystal
- guid: 90006
  name_id: 54484
  description_id: 14
  icon_set_id: 3745
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_FX_Basic_Ring.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 3004
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Sparking Beam Crystal
- guid: 90007
  name_id: 1255
  description_id: 14
  icon_set_id: 413
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_FX_Basic_Sparking.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Spiraling Beam Crystal
- guid: 90008
  name_id: 1256
  description_id: 14
  icon_set_id: 414
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_FX_Basic_Spiral.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Unstable Beam Crystal
- guid: 90009
  name_id: 1257
  description_id: 14
  icon_set_id: 416
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_FX_Basic_Unstable.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Kashyyyk Crystal
- guid: 90010
  name_id: 44509
  description_id: 14
  icon_set_id: 1996
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_FX_Kashyyk.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Forked Crystal
- guid: 90011
  name_id: 54597
  description_id: 14
  icon_set_id: 419
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_Forked.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Gungan Crystal
- guid: 90012
  name_id: 2652
  description_id: 14
  icon_set_id: 2142
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_Gungan.adr
  texture_alias: Gungan
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Mestare Crystal
- guid: 90013
  name_id: 44851
  description_id: 14
  icon_set_id: 411
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_Katana.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Short Crystal
- guid: 90014
  name_id: 1931
  description_id: 14
  icon_set_id: 417
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_Short.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Tapered Beam Crystal
- guid: 90015
  name_id: 1259
  description_id: 14
  icon_set_id: 415
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_Tapered.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Compressed Tapered Beam Crystal
- guid: 90016
  name_id: 53018
  description_id: 14
  icon_set_id: 409
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_TaperedCompressed.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Tapered Halo Crystal
- guid: 90017
  name_id: 54492
  description_id: 14
  icon_set_id: 3745
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_TaperedHalo.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 3004
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Unstable Tapered Beam Crystal
- guid: 90018
  name_id: 53017
  description_id: 14
  icon_set_id: 416
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_TaperedUnstable.adr
  texture_alias: white_square
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Dahgee Crystal
- guid: 90019
  name_id: 44197
  description_id: 14
  icon_set_id: 418
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment PrimarySaberShape
  disable_trade: false
  disable_sale: false
  model_name: Wield_LightsaberBlade_ZebraCrystal.adr
  texture_alias: ZebraCrystal
  required_gender: 0
  item_type: 1
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: true
  tint_alias: lightsaber
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
