---
# Lightsaber Beam Crystal
- guid: 90000
  name_id: 2526
  description_id: 14
  icon_set_id: 419
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_Basic.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Dark Beam Crystal
- guid: 90001
  name_id: 1258
  description_id: 14
  icon_set_id: 410
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_Darksaber.adr
  texture_alias: BlackSwirl
  item_type: 1
  tint_alias: lightsaber
# Ancient Darksaber Crystal
- guid: 90002
  name_id: 54524
  description_id: 14
  icon_set_id: 410
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_Darksaber_Ancient.adr
  texture_alias: BlackSlick
  item_type: 1
  tint_alias: lightsaber
# Cobal Crystal
- guid: 90003
  name_id: 1524
  description_id: 14
  icon_set_id: 396
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_FX_Basic_Buggy.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Compressed Beam Crystal
- guid: 90004
  name_id: 1253
  description_id: 14
  icon_set_id: 409
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_FX_Basic_Compressed.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Pulsing Beam Crystal
- guid: 90005
  name_id: 1254
  description_id: 14
  icon_set_id: 412
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_FX_Basic_Pulsing.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Radiating Ring Crystal
- guid: 90006
  name_id: 54484
  description_id: 14
  icon_set_id: 3745
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_FX_Basic_Ring.adr
  texture_alias: white_square
  item_type: 1
  composite_effect: 3004
  tint_alias: lightsaber
# Sparking Beam Crystal
- guid: 90007
  name_id: 1255
  description_id: 14
  icon_set_id: 413
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_FX_Basic_Sparking.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Spiraling Beam Crystal
- guid: 90008
  name_id: 1256
  description_id: 14
  icon_set_id: 414
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_FX_Basic_Spiral.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Unstable Beam Crystal
- guid: 90009
  name_id: 1257
  description_id: 14
  icon_set_id: 416
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_FX_Basic_Unstable.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Kashyyyk Crystal
- guid: 90010
  name_id: 44509
  description_id: 14
  icon_set_id: 1996
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_FX_Kashyyk.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Forked Crystal
- guid: 90011
  name_id: 54597
  description_id: 14
  icon_set_id: 419
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_Forked.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Gungan Crystal
- guid: 90012
  name_id: 2652
  description_id: 14
  icon_set_id: 2142
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_Gungan.adr
  texture_alias: Gungan
  item_type: 1
  tint_alias: lightsaber
# Mestare Crystal
- guid: 90013
  name_id: 44851
  description_id: 14
  icon_set_id: 411
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_Katana.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Short Crystal
- guid: 90014
  name_id: 1931
  description_id: 14
  icon_set_id: 417
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_Short.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Tapered Beam Crystal
- guid: 90015
  name_id: 1259
  description_id: 14
  icon_set_id: 415
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_Tapered.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Compressed Tapered Beam Crystal
- guid: 90016
  name_id: 53018
  description_id: 14
  icon_set_id: 409
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_TaperedCompressed.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Tapered Halo Crystal
- guid: 90017
  name_id: 54492
  description_id: 14
  icon_set_id: 3745
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_TaperedHalo.adr
  texture_alias: white_square
  item_type: 1
  composite_effect: 3004
  tint_alias: lightsaber
# Unstable Tapered Beam Crystal
- guid: 90018
  name_id: 53017
  description_id: 14
  icon_set_id: 416
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_TaperedUnstable.adr
  texture_alias: white_square
  item_type: 1
  tint_alias: lightsaber
# Dahgee Crystal
- guid: 90019
  name_id: 44197
  description_id: 14
  icon_set_id: 418
  slot: !Equipment PrimarySaberShape
  model_name: Wield_LightsaberBlade_ZebraCrystal.adr
  texture_alias: ZebraCrystal
  item_type: 1
  tint_alias: lightsaber
