---
# Blue
- guid: 100000
  name_id: 2527
  description_id: 14
  icon_set_id: 398
  tint: 20
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Green
- guid: 100001
  name_id: 2528
  description_id: 14
  icon_set_id: 399
  tint: 21
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Yellow
- guid: 100002
  name_id: 2529
  description_id: 14
  icon_set_id: 408
  tint: 22
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Orange
- guid: 100003
  name_id: 2530
  description_id: 14
  icon_set_id: 401
  tint: 23
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Red
- guid: 100004
  name_id: 2531
  description_id: 14
  icon_set_id: 404
  tint: 24
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Purple
- guid: 100005
  name_id: 2532
  description_id: 14
  icon_set_id: 403
  tint: 25
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Silver
- guid: 100006
  name_id: 2533
  description_id: 14
  icon_set_id: 405
  tint: 26
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Teal
- guid: 100007
  name_id: 2534
  description_id: 14
  icon_set_id: 406
  tint: 27
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Pink
- guid: 100008
  name_id: 2535
  description_id: 14
  icon_set_id: 402
  tint: 28
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Light Green
- guid: 100009
  name_id: 2536
  description_id: 14
  icon_set_id: 400
  tint: 29
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# White
- guid: 100010
  name_id: 2537
  description_id: 14
  icon_set_id: 407
  tint: 30
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Black
- guid: 100011
  name_id: 2538
  description_id: 14
  icon_set_id: 397
  tint: 31
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
# Sith Crystal
- guid: 100012
  name_id: 51152
  description_id: 14
  icon_set_id: 2772
  tint: 47
  item_class: -1
  slot: !Equipment PrimarySaberColor
  item_type: 1
  max_stack_size: 1
