---
duel_construction_chamber_singleplayer:
  guid: 205
  max_players: 1
  template_name: 13703
  asset_name: LD_Yoda
  hide_ui: false
  is_combat: false
  default_point_of_interest:
    guid: 205
    pos:
      x: 230.9804
      y: 200
      z: 227.3198
      w: 1
    rot:
      x: 0
      y: 0
      z: 0
      w: 0
  speed: 0
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
