---
# Red Eyes
- guid: 150000
  name_id: 428
  description_id: 14
  icon_set_id: 710
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 200
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 9
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150000
  unknown40: 0
  stats: []
  abilities: []
# Brown Eyes
- guid: 150001
  name_id: 422
  description_id: 14
  icon_set_id: 706
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 9
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150001
  unknown40: 0
  stats: []
  abilities: []
# Yellow Eyes
- guid: 150002
  name_id: 420
  description_id: 14
  icon_set_id: 711
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 200
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 9
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150002
  unknown40: 0
  stats: []
  abilities: []
# Green Eyes
- guid: 150003
  name_id: 430
  description_id: 14
  icon_set_id: 707
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 9
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150003
  unknown40: 0
  stats: []
  abilities: []
# Blue Eyes
- guid: 150004
  name_id: 424
  description_id: 14
  icon_set_id: 705
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 9
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150004
  unknown40: 0
  stats: []
  abilities: []
# Purple Eyes
- guid: 150005
  name_id: 432
  description_id: 14
  icon_set_id: 709
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 150
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 9
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150005
  unknown40: 0
  stats: []
  abilities: []
# Magenta Eyes
- guid: 150006
  name_id: 434
  description_id: 14
  icon_set_id: 708
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 400
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 9
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150006
  unknown40: 0
  stats: []
  abilities: []
# Black Eyes
- guid: 150007
  name_id: 426
  description_id: 14
  icon_set_id: 704
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 100
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 9
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150007
  unknown40: 0
  stats: []
  abilities: []
# Red Eyes
- guid: 150008
  name_id: 43485
  description_id: 14
  icon_set_id: 1809
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 200
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 12
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150008
  unknown40: 0
  stats: []
  abilities: []
# Orange Eyes
- guid: 150009
  name_id: 43484
  description_id: 14
  icon_set_id: 1808
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 400
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 12
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150009
  unknown40: 0
  stats: []
  abilities: []
# Yellow Eyes
- guid: 150010
  name_id: 420
  description_id: 14
  icon_set_id: 1811
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 200
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 12
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150010
  unknown40: 0
  stats: []
  abilities: []
# Yellow Green Eyes
- guid: 150011
  name_id: 43488
  description_id: 14
  icon_set_id: 1812
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 300
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 12
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150011
  unknown40: 0
  stats: []
  abilities: []
# Teal Eyes
- guid: 150012
  name_id: 43486
  description_id: 14
  icon_set_id: 1810
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 300
  item_class: -1
  required_battle_class: 0
  slot: !Customization EyeColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 12
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: EyeColor
  customization_id: 150012
  unknown40: 0
  stats: []
  abilities: []
