---
# Orange Hair
- guid: 30000
  name_id: 452
  description_id: 14
  icon_set_id: 755
  tint: 0
  cost: 200
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140000
# Red Hair
- guid: 30001
  name_id: 454
  description_id: 14
  icon_set_id: 757
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140001
# Blonde Hair
- guid: 30002
  name_id: 440
  description_id: 14
  icon_set_id: 749
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140002
# Dirty Blonde Hair
- guid: 30003
  name_id: 442
  description_id: 14
  icon_set_id: 750
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140003
# Light Brown Hair
- guid: 30004
  name_id: 444
  description_id: 14
  icon_set_id: 753
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140004
# Brown Hair
- guid: 30005
  name_id: 446
  description_id: 14
  icon_set_id: 751
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140005
# Dark Green Hair
- guid: 30006
  name_id: 450
  description_id: 14
  icon_set_id: 754
  tint: 0
  cost: 100
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140006
# Dark Blue Hair
- guid: 30007
  name_id: 18047
  description_id: 14
  icon_set_id: 3598
  tint: 0
  cost: 200
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140007
# Dark Purple Hair
- guid: 30008
  name_id: 448
  description_id: 14
  icon_set_id: 756
  tint: 0
  cost: 100
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140008
# White Hair
- guid: 30009
  name_id: 93
  description_id: 14
  icon_set_id: 758
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140009
# Grey Hair
- guid: 30010
  name_id: 91
  description_id: 14
  icon_set_id: 752
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140010
# Black Hair
- guid: 30011
  name_id: 95
  description_id: 14
  icon_set_id: 748
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 6
  customization_slot: HairColor
  customization_id: 140011
# Red
- guid: 30012
  name_id: 2634
  description_id: 14
  icon_set_id: 724
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 5
  customization_slot: HairColor
  customization_id: 140012
# Blue
- guid: 30013
  name_id: 2630
  description_id: 14
  icon_set_id: 722
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 5
  customization_slot: HairColor
  customization_id: 140013
# Purple
- guid: 30014
  name_id: 2632
  description_id: 14
  icon_set_id: 723
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 5
  customization_slot: HairColor
  customization_id: 140014
# Dark Red Hair
- guid: 30015
  name_id: 18049
  description_id: 14
  icon_set_id: 1313
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 10
  customization_slot: HairColor
  customization_id: 140015
# Yellow-Green Hair
- guid: 30016
  name_id: 18050
  description_id: 14
  icon_set_id: 1309
  tint: 0
  cost: 100
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 10
  customization_slot: HairColor
  customization_id: 140016
# Teal Hair
- guid: 30017
  name_id: 18046
  description_id: 14
  icon_set_id: 1310
  tint: 0
  cost: 100
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 10
  customization_slot: HairColor
  customization_id: 140017
# Dark Blue Hair
- guid: 30018
  name_id: 18047
  description_id: 14
  icon_set_id: 1315
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 10
  customization_slot: HairColor
  customization_id: 140018
# Purple Hair
- guid: 30019
  name_id: 18044
  description_id: 14
  icon_set_id: 1311
  tint: 0
  cost: 100
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 10
  customization_slot: HairColor
  customization_id: 140019
# Dark Purple Hair
- guid: 30020
  name_id: 18048
  description_id: 14
  icon_set_id: 1314
  tint: 0
  cost: 50
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 10
  customization_slot: HairColor
  customization_id: 140020
# Pink Hair
- guid: 30021
  name_id: 18045
  description_id: 14
  icon_set_id: 1312
  tint: 0
  cost: 200
  item_class: -1
  required_battle_class: 0
  slot: !Customization HairColor
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 0
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  race_set_id: 10
  customization_slot: HairColor
  customization_id: 140021
