---
# Chin Scar
- guid: 50000
  name_id: 792
  description_id: 14
  icon_set_id: 607
  cost: 50
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170000
# Crescent Scar
- guid: 50001
  name_id: 590
  description_id: 14
  icon_set_id: 604
  cost: 100
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170001
# Eye Scar
- guid: 50002
  name_id: 584
  description_id: 14
  icon_set_id: 601
  cost: 50
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170002
# Full Scar
- guid: 50003
  name_id: 588
  description_id: 14
  icon_set_id: 602
  cost: 50
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170003
# Hardcase Tattoo
- guid: 50004
  name_id: 54304
  description_id: 14
  icon_set_id: 3655
  cost: 100
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170004
# Lefty Scar
- guid: 50005
  name_id: 576
  description_id: 14
  icon_set_id: 605
  cost: 50
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170005
# No Pattern
- guid: 50006
  name_id: 2600
  description_id: 14
  icon_set_id: 588
  cost: 20
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170006
# Republic Tattoo
- guid: 50007
  name_id: 592
  description_id: 14
  icon_set_id: 606
  cost: 200
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170007
# Side Scar
- guid: 50008
  name_id: 586
  description_id: 14
  icon_set_id: 603
  cost: 50
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170008
# Square Tattoo
- guid: 50009
  name_id: 582
  description_id: 14
  icon_set_id: 608
  cost: 100
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170009
# Track Tattoo
- guid: 50010
  name_id: 580
  description_id: 14
  icon_set_id: 609
  cost: 100
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170010
# Whiskers
- guid: 50011
  name_id: 578
  description_id: 14
  icon_set_id: 610
  cost: 50
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170011
- guid: 50012
  description_id: 14
  cost: 50
  slot: !Customization FacePattern
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 2
  customization_slot: FacePattern
  customization_id: 170012
# Aayla's Lekku Wraps
- guid: 50013
  name_id: 13853
  description_id: 14
  icon_set_id: 636
  cost: 150
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: FacePattern
  customization_id: 170013
# Aayla's Lekku Pattern
- guid: 50014
  name_id: 13854
  description_id: 14
  icon_set_id: 635
  cost: 300
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: FacePattern
  customization_id: 170014
# Lekku Crescents Pattern
- guid: 50015
  name_id: 13849
  description_id: 14
  icon_set_id: 633
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: FacePattern
  customization_id: 170015
# Lekku Crosswraps
- guid: 50016
  name_id: 13850
  description_id: 14
  icon_set_id: 634
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: FacePattern
  customization_id: 170016
# Lekku Spots Pattern
- guid: 50017
  name_id: 13856
  description_id: 14
  icon_set_id: 637
  cost: 150
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: FacePattern
  customization_id: 170017
# Lekku Stripes Pattern
- guid: 50018
  name_id: 13857
  description_id: 14
  icon_set_id: 638
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: FacePattern
  customization_id: 170018
# Lekku Suncircle Pattern
- guid: 50019
  name_id: 13858
  description_id: 14
  icon_set_id: 640
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: FacePattern
  customization_id: 170019
# Lekku Swirls Pattern
- guid: 50020
  name_id: 13848
  description_id: 14
  icon_set_id: 639
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: FacePattern
  customization_id: 170020
# No Pattern
- guid: 50021
  name_id: 2600
  description_id: 14
  icon_set_id: 1164
  cost: 20
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: FacePattern
  customization_id: 170021
# Claw Pattern
- guid: 50022
  name_id: 15438
  description_id: 14
  icon_set_id: 656
  cost: 500
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170022
# Crawl Pattern
- guid: 50023
  name_id: 13873
  description_id: 14
  icon_set_id: 657
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170023
# Crescent Pattern
- guid: 50024
  name_id: 13872
  description_id: 14
  icon_set_id: 658
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170024
# Diamond Pattern
- guid: 50025
  name_id: 33042
  description_id: 14
  icon_set_id: 1633
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170025
# Eeth's Pattern
- guid: 50026
  name_id: 13866
  description_id: 14
  icon_set_id: 662
  cost: 200
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170026
# Fire Pattern
- guid: 50027
  name_id: 33044
  description_id: 14
  icon_set_id: 1634
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170027
# Flame Pattern
- guid: 50028
  name_id: 13870
  description_id: 14
  icon_set_id: 660
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170028
# Kass' Pattern
- guid: 50029
  name_id: 13867
  description_id: 14
  icon_set_id: 661
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170029
# Line Pattern
- guid: 50030
  name_id: 13871
  description_id: 14
  icon_set_id: 663
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170030
# Opress Pattern
- guid: 50031
  name_id: 33046
  description_id: 14
  icon_set_id: 1635
  cost: 200
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170031
# Strips Pattern
- guid: 50032
  name_id: 33048
  description_id: 14
  icon_set_id: 1636
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170032
# Sugi's Pattern
- guid: 50033
  name_id: 13865
  description_id: 14
  icon_set_id: 664
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170033
# Swoop Pattern
- guid: 50034
  name_id: 15439
  description_id: 14
  icon_set_id: 665
  cost: 600
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170034
# Triangle Pattern
- guid: 50035
  name_id: 13869
  description_id: 14
  icon_set_id: 666
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170035
# Zabrak Sith Pattern
- guid: 50036
  name_id: 13868
  description_id: 14
  icon_set_id: 659
  cost: 600
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: FacePattern
  customization_id: 170036
# Curl Pattern
- guid: 50037
  name_id: 598
  description_id: 14
  icon_set_id: 620
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: FacePattern
  customization_id: 170037
# Dot Pattern
- guid: 50038
  name_id: 596
  description_id: 14
  icon_set_id: 621
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: FacePattern
  customization_id: 170038
# Eyebrow Pattern
- guid: 50039
  name_id: 600
  description_id: 14
  icon_set_id: 622
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: FacePattern
  customization_id: 170039
# Lightning Pattern
- guid: 50040
  name_id: 604
  description_id: 14
  icon_set_id: 1372
  cost: 150
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: FacePattern
  customization_id: 170040
# Shaak Pattern
- guid: 50041
  name_id: 1870
  description_id: 14
  icon_set_id: 1371
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: FacePattern
  customization_id: 170041
# Stacks Pattern
- guid: 50042
  name_id: 15427
  description_id: 14
  icon_set_id: 623
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: FacePattern
  customization_id: 170042
# Teardrop Pattern
- guid: 50043
  name_id: 602
  description_id: 14
  icon_set_id: 624
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: FacePattern
  customization_id: 170043
# V Pattern
- guid: 50044
  name_id: 13877
  description_id: 14
  icon_set_id: 619
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: FacePattern
  customization_id: 170044
# Brow Arc Pattern
- guid: 50045
  name_id: 18064
  description_id: 14
  icon_set_id: 1297
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170045
# Chicho Pattern
- guid: 50046
  name_id: 18062
  description_id: 14
  icon_set_id: 1298
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170046
# Chin Arc Pattern
- guid: 50047
  name_id: 18063
  description_id: 14
  icon_set_id: 1299
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170047
# Chuchi Pattern
- guid: 50048
  name_id: 18058
  description_id: 14
  icon_set_id: 1300
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170048
# Crooked  Pattern
- guid: 50049
  name_id: 18069
  description_id: 14
  icon_set_id: 1301
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170049
# Guard Pattern
- guid: 50050
  name_id: 18059
  description_id: 14
  icon_set_id: 1302
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170050
# Ion Pattern
- guid: 50051
  name_id: 18061
  description_id: 14
  icon_set_id: 1303
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170051
# Lines Pattern
- guid: 50052
  name_id: 18065
  description_id: 14
  icon_set_id: 1304
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170052
# Papanoida Pattern
- guid: 50053
  name_id: 18060
  description_id: 14
  icon_set_id: 1305
  cost: 200
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170053
# Slope Pattern
- guid: 50054
  name_id: 18066
  description_id: 14
  icon_set_id: 1306
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170054
# Squares  Pattern
- guid: 50055
  name_id: 18068
  description_id: 14
  icon_set_id: 1307
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170055
# T-bone  Pattern
- guid: 50056
  name_id: 18067
  description_id: 14
  icon_set_id: 1308
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: FacePattern
  customization_id: 170056
# Garnac Pattern
- guid: 50057
  name_id: 43477
  description_id: 14
  icon_set_id: 1823
  cost: 500
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: FacePattern
  customization_id: 170057
# Mask Pattern
- guid: 50058
  name_id: 43478
  description_id: 14
  icon_set_id: 1824
  cost: 200
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: FacePattern
  customization_id: 170058
# Mohawk Pattern
- guid: 50059
  name_id: 43479
  description_id: 14
  icon_set_id: 1825
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: FacePattern
  customization_id: 170059
# Scratch Pattern
- guid: 50060
  name_id: 43480
  description_id: 14
  icon_set_id: 1826
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: FacePattern
  customization_id: 170060
# Simple Pattern
- guid: 50061
  name_id: 43481
  description_id: 14
  icon_set_id: 1827
  cost: 50
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: FacePattern
  customization_id: 170061
# Sunfire Pattern
- guid: 50062
  name_id: 43482
  description_id: 14
  icon_set_id: 1828
  cost: 100
  slot: !Customization FacePattern
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: FacePattern
  customization_id: 170062
