---
# Pale Skin
- guid: 60000
  name_id: 554
  description_id: 14
  icon_set_id: 715
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 1
  customization_slot: SkinTone
  customization_id: 120000
# Peach Skin
- guid: 60001
  name_id: 13874
  description_id: 14
  icon_set_id: 716
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 1
  customization_slot: SkinTone
  customization_id: 120001
# Golden Skin
- guid: 60002
  name_id: 553
  description_id: 14
  icon_set_id: 713
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 1
  customization_slot: SkinTone
  customization_id: 120002
# Warm Tan Skin
- guid: 60003
  name_id: 556
  description_id: 14
  icon_set_id: 718
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 1
  customization_slot: SkinTone
  customization_id: 120003
# Tan Skin
- guid: 60004
  name_id: 13876
  description_id: 14
  icon_set_id: 717
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 1
  customization_slot: SkinTone
  customization_id: 120004
# Brown Skin
- guid: 60005
  name_id: 13875
  description_id: 14
  icon_set_id: 714
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 1
  customization_slot: SkinTone
  customization_id: 120005
# Brown Skin
- guid: 60006
  name_id: 13875
  description_id: 14
  icon_set_id: 712
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 1
  customization_slot: SkinTone
  customization_id: 120006
# Blue Skin
- guid: 60007
  name_id: 552
  description_id: 14
  icon_set_id: 728
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120007
# Teal Skin
- guid: 60008
  name_id: 562
  description_id: 14
  icon_set_id: 734
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120008
# Green Skin
- guid: 60009
  name_id: 558
  description_id: 14
  icon_set_id: 731
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120009
# Yellow Skin
- guid: 60010
  name_id: 563
  description_id: 14
  icon_set_id: 735
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120010
# Peach Skin
- guid: 60011
  name_id: 561
  description_id: 14
  icon_set_id: 733
  cost: 50
  slot: !Customization SkinTone
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120011
# Orange Skin
- guid: 60012
  name_id: 560
  description_id: 14
  icon_set_id: 732
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120012
# Brown Skin
- guid: 60013
  name_id: 770
  description_id: 14
  icon_set_id: 729
  cost: 50
  slot: !Customization SkinTone
  required_gender: 1
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120013
# Grey Skin
- guid: 60014
  name_id: 559
  description_id: 14
  icon_set_id: 730
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120014
# Red Skin
- guid: 60015
  name_id: 1249
  description_id: 14
  icon_set_id: 738
  cost: 100
  slot: !Customization SkinTone
  required_gender: 2
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120015
# Pink Skin
- guid: 60016
  name_id: 1251
  description_id: 14
  icon_set_id: 739
  cost: 100
  slot: !Customization SkinTone
  required_gender: 2
  item_type: 12
  max_stack_size: 2
  race_set_id: 3
  customization_slot: SkinTone
  customization_id: 120016
# Khaki Skin
- guid: 60017
  name_id: 782
  description_id: 14
  icon_set_id: 745
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: SkinTone
  customization_id: 120017
# Yellow Skin
- guid: 60018
  name_id: 780
  description_id: 14
  icon_set_id: 747
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: SkinTone
  customization_id: 120018
# Red Skin
- guid: 60019
  name_id: 776
  description_id: 14
  icon_set_id: 746
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: SkinTone
  customization_id: 120019
# Brown Skin
- guid: 60020
  name_id: 778
  description_id: 14
  icon_set_id: 744
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 4
  customization_slot: SkinTone
  customization_id: 120020
# Amber Skin
- guid: 60021
  name_id: 772
  description_id: 14
  icon_set_id: 725
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: SkinTone
  customization_id: 120021
# Orange Skin
- guid: 60022
  name_id: 15428
  description_id: 14
  icon_set_id: 726
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: SkinTone
  customization_id: 120022
# Red Skin
- guid: 60023
  name_id: 774
  description_id: 14
  icon_set_id: 727
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 5
  customization_slot: SkinTone
  customization_id: 120023
# Pantoran Blue
- guid: 60024
  name_id: 1681
  description_id: 14
  icon_set_id: 1316
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 10
  customization_slot: SkinTone
  customization_id: 120024
# Grey Scales
- guid: 60025
  name_id: 43475
  description_id: 14
  icon_set_id: 1806
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: SkinTone
  customization_id: 120025
# Green Scales
- guid: 60026
  name_id: 43483
  description_id: 14
  icon_set_id: 1805
  cost: 50
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: SkinTone
  customization_id: 120026
# Bright Green Scales
- guid: 60027
  name_id: 43473
  description_id: 14
  icon_set_id: 1803
  cost: 100
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: SkinTone
  customization_id: 120027
# Yellow Scales
- guid: 60028
  name_id: 43474
  description_id: 14
  icon_set_id: 1807
  cost: 100
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: SkinTone
  customization_id: 120028
# Brown Scales
- guid: 60029
  name_id: 43476
  description_id: 14
  icon_set_id: 1804
  cost: 100
  slot: !Customization SkinTone
  item_type: 12
  max_stack_size: 2
  race_set_id: 12
  customization_slot: SkinTone
  customization_id: 120029
