---
# Start of male species
# Clone
- guid: 70000
  name_id: 436
  description_id: 14
  icon_set_id: 1171
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 1
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180000
  unknown40: 0
  stats: []
  abilities: []
# Human
- guid: 70001
  name_id: 4
  description_id: 14
  icon_set_id: 1173
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 1
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180001
  unknown40: 0
  stats: []
  abilities: []
# Pantoran
- guid: 70002
  name_id: 1677
  description_id: 14
  icon_set_id: 1318
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 1
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180002
  unknown40: 0
  stats: []
  abilities: []
# Togruta
- guid: 70003
  name_id: 439
  description_id: 14
  icon_set_id: 1175
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 1
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180003
  unknown40: 0
  stats: []
  abilities: []
# Trandoshan
- guid: 70004
  name_id: 2174
  description_id: 14
  icon_set_id: 1849
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 1
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180004
  unknown40: 0
  stats: []
  abilities: []
# Twi'lek
- guid: 70005
  name_id: 437
  description_id: 14
  icon_set_id: 1177
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 1
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180005
  unknown40: 0
  stats: []
  abilities: []
# Zabrak
- guid: 70006
  name_id: 438
  description_id: 14
  icon_set_id: 1179
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 1
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180006
  unknown40: 0
  stats: []
  abilities: []
# Start of female species
# Human
- guid: 70007
  name_id: 4
  description_id: 14
  icon_set_id: 1172
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 2
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180007
  unknown40: 0
  stats: []
  abilities: []
# Pantoran
- guid: 70008
  name_id: 1677
  description_id: 14
  icon_set_id: 1317
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 2
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180008
  unknown40: 0
  stats: []
  abilities: []
# Togruta
- guid: 70009
  name_id: 439
  description_id: 14
  icon_set_id: 1174
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 2
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180009
  unknown40: 0
  stats: []
  abilities: []
# Trandoshan
- guid: 70010
  name_id: 2174
  description_id: 14
  icon_set_id: 1850
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 2
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180010
  unknown40: 0
  stats: []
  abilities: []
# Twi'lek
- guid: 70011
  name_id: 437
  description_id: 14
  icon_set_id: 1176
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 2
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180011
  unknown40: 0
  stats: []
  abilities: []
# Zabrak
- guid: 70012
  name_id: 438
  description_id: 14
  icon_set_id: 1178
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 600
  item_class: -1
  required_battle_class: 0
  slot: !Customization None
  disable_trade: false
  disable_sale: false
  model_name: ''
  texture_alias: ''
  required_gender: 2
  item_type: 12
  category: 0
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 2
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: BodyModel
  customization_id: 180012
  unknown40: 0
  stats: []
  abilities: []