---
# Diver Padm√© Amidala's Helmet
- guid: 200000
  name_id: 2358
  description_id: 14
  icon_set_id: 2327
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_PadmeScubaHelmet.adr
  texture_alias: PadmeScuba
  item_type: 1
  category: 60
# Senator Ballroom Garb
- guid: 200001
  name_id: 1583
  description_id: 14
  icon_set_id: 1929
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_NabooBallroom.adr
  texture_alias: NabooFormal
  item_type: 1
  category: 61
# Senator Ballroom Gloves
- guid: 200002
  name_id: 1581
  description_id: 14
  icon_set_id: 1931
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_NabooBallroomGloves.adr
  texture_alias: NabooFormal
  item_type: 1
  category: 62
# Senator Ballroom Shoes
- guid: 200003
  name_id: 1585
  description_id: 14
  icon_set_id: 1930
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_NabooBallroom.adr
  texture_alias: NabooFormal
  item_type: 1
  category: 63
# Senator Kharrus' Robes
- guid: 200004
  name_id: 1654
  description_id: 14
  icon_set_id: 1927
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SenatorKharrusRobe.adr
  texture_alias: SenatorKharrus
  item_type: 1
  category: 61
  members: true
# Senator Kharrus' Boots
- guid: 200005
  name_id: 1656
  description_id: 14
  icon_set_id: 1928
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_SenatorialNabooBoots.adr
  texture_alias: SenatorKharrus
  item_type: 1
  category: 63
  members: true
# Palpatine's Robes
- guid: 200006
  name_id: 20387
  description_id: 14
  icon_set_id: 1102
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_PalpatineRobe.adr
  texture_alias: Palpatine
  item_type: 1
  category: 61
  members: true
# Palpatine's Shoes
- guid: 200007
  name_id: 1354
  description_id: 14
  icon_set_id: 1103
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_LokDurdBoots.adr
  texture_alias: Palpatine
  item_type: 1
  category: 63
  members: true
# Bail Organa's Robes
- guid: 200008
  name_id: 1612
  description_id: 14
  icon_set_id: 1244
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_BailOrganaSuit.adr
  texture_alias: BailOrgana
  item_type: 1
  category: 61
  members: true
# Bail Organa's Boots
- guid: 200009
  name_id: 1614
  description_id: 14
  icon_set_id: 1245
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_BailOrganaBoots.adr
  texture_alias: BailOrgana
  item_type: 1
  category: 63
  members: true
# Admiral Yularen's Uniform
- guid: 200010
  name_id: 136
  description_id: 14
  icon_set_id: 116
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_WullfYularenUniform.adr
  texture_alias: WullfYularen
  item_type: 1
  category: 61
  members: true
# Republic Fleet Officer Gloves
- guid: 200011
  name_id: 312
  description_id: 14
  icon_set_id: 181
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_ShortGloves.adr
  texture_alias: OfficerGrey
  item_type: 1
  category: 62
  members: true
# Republic Fleet Officer Boots
- guid: 200012
  name_id: 310
  description_id: 14
  icon_set_id: 139
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_HeeledRidgeBoots.adr
  texture_alias: OfficerGrey
  item_type: 1
  category: 63
  members: true
# Orn Free Taa's Robes
- guid: 200013
  name_id: 878
  description_id: 14
  icon_set_id: 481
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_OrnFreeTaRobes.adr
  texture_alias: OrnFreeTa
  item_type: 1
  category: 61
  members: true
# Orn Free Taa's Boots
- guid: 200014
  name_id: 880
  description_id: 14
  icon_set_id: 482
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_LokDurdBoots.adr
  texture_alias: OrnFreeTa
  item_type: 1
  category: 63
  members: true
# Republic Technician's Jumpsuit
- guid: 200015
  name_id: 850
  description_id: 14
  icon_set_id: 464
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_FleetMechanicJumpsuit.adr
  texture_alias: FleetMechanic
  item_type: 1
  category: 61
  members: true
# Republic Technician's Helmet
- guid: 200016
  name_id: 846
  description_id: 14
  icon_set_id: 467
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_FleetMechanicHelmet.adr
  texture_alias: FleetMechanic
  item_type: 1
  category: 60
  members: true
# Republic Technician's Gloves
- guid: 200017
  name_id: 848
  description_id: 14
  icon_set_id: 466
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_ShortGloves.adr
  texture_alias: FleetMechanic
  item_type: 1
  category: 62
  members: true
# Republic Technician's Boots
- guid: 200018
  name_id: 852
  description_id: 14
  icon_set_id: 465
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_HeeledRidgeBoots.adr
  texture_alias: FleetMechanic
  item_type: 1
  category: 63
  members: true
# Medical Officer Uniform
- guid: 200019
  name_id: 874
  description_id: 14
  icon_set_id: 377
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_OfficerUniform.adr
  texture_alias: OfficerWhite
  item_type: 1
  category: 61
  members: true
# Medical Officer Cap
- guid: 200020
  name_id: 870
  description_id: 14
  icon_set_id: 395
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_OfficerCap.adr
  texture_alias: OfficerWhite
  item_type: 1
  category: 60
  members: true
# Medical Officer Gloves
- guid: 200021
  name_id: 872
  description_id: 14
  icon_set_id: 389
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_ShortGloves.adr
  texture_alias: OfficerWhite
  item_type: 1
  category: 62
  members: true
# Medical Officer Boots
- guid: 200022
  name_id: 876
  description_id: 14
  icon_set_id: 383
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_HeeledRidgeBoots.adr
  texture_alias: OfficerWhite
  item_type: 1
  category: 63
  members: true
# General Snow Uniform Coat
- guid: 200023
  name_id: 856
  description_id: 14
  icon_set_id: 471
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_GeneralSnowUniform.adr
  texture_alias: GeneralSnowUniform
  item_type: 1
  category: 61
# General Snow Uniform Hood
- guid: 200024
  name_id: 860
  description_id: 14
  icon_set_id: 475
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_GeneralSnowHoodieUp.adr
  texture_alias: GeneralSnowUniform
  item_type: 1
  category: 60
# General Snow Uniform Gloves
- guid: 200025
  name_id: 854
  description_id: 14
  icon_set_id: 473
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_GeneralSnowGauntlets.adr
  texture_alias: GeneralSnowUniform
  item_type: 1
  category: 62
# General Snow Uniform Boots
- guid: 200026
  name_id: 858
  description_id: 14
  icon_set_id: 472
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_GeneralSnowBoots.adr
  texture_alias: GeneralSnowUniform
  item_type: 1
  category: 63
