---
# Han Solo's Outfit
- guid: 10164
  name_id: 302
  description_id: 14
  icon_set_id: 96
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment Body
  disable_trade: false
  disable_sale: false
  model_name: Wear_Human_<gender>_Body_HanSoloSuit.adr
  texture_alias: HanSolo
  required_gender: 0
  item_type: 1
  category: 61
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Han Solo's Boots
- guid: 40160
  name_id: 304
  description_id: 14
  icon_set_id: 138
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment Feet
  disable_trade: false
  disable_sale: false
  model_name: Wear_Human_<gender>_Feet_HanSoloBoots.adr
  texture_alias: HanSolo
  required_gender: 0
  item_type: 1
  category: 63
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Lando Calrissian's Suit
- guid: 10184
  name_id: 1462
  description_id: 14
  icon_set_id: 1100
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment Body
  disable_trade: false
  disable_sale: false
  model_name: Wear_Human_<gender>_Body_LandoSuit.adr
  texture_alias: Lando
  required_gender: 0
  item_type: 1
  category: 61
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Lando Calrissian's Shoes
- guid: 40184
  name_id: 1472
  description_id: 14
  icon_set_id: 1101
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment Feet
  disable_trade: false
  disable_sale: false
  model_name: Wear_Human_<gender>_Feet_LandoShoes.adr
  texture_alias: Lando
  required_gender: 0
  item_type: 1
  category: 63
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Kyle Katarn's Uniform
- guid: 10180
  name_id: 204
  description_id: 14
  icon_set_id: 100
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment Body
  disable_trade: false
  disable_sale: false
  model_name: Wear_Human_<gender>_Body_KyleKatarnSuit.adr
  texture_alias: KyleKatarn
  required_gender: 0
  item_type: 1
  category: 61
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
# Kyle Katarn's Gloves
- guid: 30156
  name_id: 202
  description_id: 14
  icon_set_id: 171
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment Hands
  disable_trade: false
  disable_sale: false
  model_name: Wear_Human_<gender>_Hands_KyleKatarnGloves.adr
  texture_alias: KyleKatarn
  required_gender: 0
  item_type: 1
  category: 62
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
