---
# Bravis Sith Suit
- guid: 220000
  name_id: 1325
  description_id: 14
  icon_set_id: 1113
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SparkingCrystalSuit.adr
  texture_alias: SparkingCrystal
  item_type: 1
  category: 61
  members: true
  max_stack_size: 1
# Bravis Sith Hood
- guid: 220001
  name_id: 1420
  description_id: 14
  icon_set_id: 1116
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_SparkingCrystalHood.adr
  texture_alias: SparkingCrystal
  item_type: 1
  category: 60
  members: true
  max_stack_size: 1
# Bravis Sith Gloves
- guid: 220002
  name_id: 1378
  description_id: 14
  icon_set_id: 1115
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_CloneSnowGloves.adr
  texture_alias: SparkingCrystal
  item_type: 1
  category: 62
  members: true
  max_stack_size: 1
# Bravis Sith Boots
- guid: 220003
  name_id: 1360
  description_id: 14
  icon_set_id: 1114
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_SparkingCrystalBoots.adr
  texture_alias: SparkingCrystal
  item_type: 1
  category: 63
  members: true
  max_stack_size: 1
# Savek Sith Suit
- guid: 220004
  name_id: 886
  description_id: 14
  icon_set_id: 487
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_UnstableCrystalSuit.adr
  texture_alias: SithArmor
  item_type: 1
  category: 61
  members: true
  max_stack_size: 1
# Savek Sith Hood
- guid: 220005
  name_id: 882
  description_id: 14
  icon_set_id: 490
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_UnstableCrystalHood.adr
  texture_alias: SithArmor
  item_type: 1
  category: 60
  members: true
  max_stack_size: 1
# Savek Sith Gloves
- guid: 220006
  name_id: 884
  description_id: 14
  icon_set_id: 489
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_UnstableCrystalGloves.adr
  texture_alias: SithArmor
  item_type: 1
  category: 62
  members: true
  max_stack_size: 1
# Savek Sith Boots
- guid: 220007
  name_id: 888
  description_id: 14
  icon_set_id: 488
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_UnstableCrystalBoots.adr
  texture_alias: SithArmor
  item_type: 1
  category: 63
  members: true
  max_stack_size: 1
# Moralo Eval's Prison Outfit
- guid: 220008
  name_id: 4588
  description_id: 14
  icon_set_id: 2660
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_MoraloEvalJumpsuit.adr
  texture_alias: MoraloEval
  item_type: 1
  category: 61
  members: true
  max_stack_size: 1
# Lux Bonteri's Suit
- guid: 220009
  name_id: 4548
  description_id: 14
  icon_set_id: 2630
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_LuxBonteriOutfit.adr
  texture_alias: LuxBonteri
  item_type: 1
  category: 61
  max_stack_size: 1
# Lux Bonteri's Beanie
- guid: 220010
  name_id: 4546
  description_id: 14
  icon_set_id: 2628
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_LuxBonteriBeanie.adr
  texture_alias: LuxBonteri
  item_type: 1
  category: 60
  max_stack_size: 1
# Lux Bonteri's Gloves
- guid: 220011
  name_id: 4547
  description_id: 14
  icon_set_id: 2629
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_ShortGloves.adr
  texture_alias: LuxBonteri
  item_type: 1
  category: 62
  max_stack_size: 1
# Lux Bonteri's Boots
- guid: 220012
  name_id: 4549
  description_id: 14
  icon_set_id: 2631
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_LuxBonteriBoots.adr
  texture_alias: LuxBonteri
  item_type: 1
  category: 63
  max_stack_size: 1
# Count Dooku's Original Robes
- guid: 220013
  name_id: 1309
  description_id: 14
  icon_set_id: 1080
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_CountDooku.adr
  texture_alias: CountDooku
  item_type: 1
  category: 61
  max_stack_size: 1
# Count Dooku's Original Boots
- guid: 220014
  name_id: 1305
  description_id: 14
  icon_set_id: 1081
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_CountDooku.adr
  texture_alias: CountDooku
  item_type: 1
  category: 63
  max_stack_size: 1
# Count Dooku's Robes
- guid: 220015
  name_id: 32929
  description_id: 14
  icon_set_id: 1080
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_CountDooku.adr
  texture_alias: CountDookuV2
  item_type: 1
  category: 61
  max_stack_size: 1
# Count Dooku's Boots
- guid: 220016
  name_id: 32930
  description_id: 14
  icon_set_id: 1081
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_CountDooku.adr
  texture_alias: CountDookuV2
  item_type: 1
  category: 63
  max_stack_size: 1
# Captain Argyus' Armor
- guid: 220017
  name_id: 8918
  description_id: 14
  icon_set_id: 109
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SenateGuardArmor.adr
  texture_alias: CaptArgyus
  item_type: 1
  category: 61
  max_stack_size: 1
# Captain Argyus' Helmet
- guid: 220018
  name_id: 8924
  description_id: 14
  icon_set_id: 206
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_SenateGuardHelm.adr
  texture_alias: CaptArgyus
  item_type: 1
  category: 60
  max_stack_size: 1
# Captain Argyus' Gloves
- guid: 220019
  name_id: 8922
  description_id: 14
  icon_set_id: 178
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_SenateGuardGloves.adr
  texture_alias: CaptArgyus
  item_type: 1
  category: 62
  max_stack_size: 1
# Captain Argyus' Boots
- guid: 220020
  name_id: 8920
  description_id: 14
  icon_set_id: 132
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_CloneBoots.adr
  texture_alias: CaptArgyus
  item_type: 1
  category: 63
  max_stack_size: 1
# Osi Sobeck's Suit
- guid: 220021
  name_id: 43189
  description_id: 14
  icon_set_id: 1787
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_OsiSobeck.adr
  texture_alias: Osi
  item_type: 1
  category: 61
  members: true
  max_stack_size: 1
# Osi Sobeck's Bracers
- guid: 220022
  name_id: 43188
  description_id: 14
  icon_set_id: 1788
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_OsiSobeckGauntlets.adr
  texture_alias: Osi
  item_type: 1
  category: 62
  members: true
  max_stack_size: 1
# Separatist Scientist's Coat
- guid: 220023
  name_id: 1311
  description_id: 14
  icon_set_id: 1084
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_DrNuvoVindiCoat.adr
  texture_alias: DrNuvoVindi
  item_type: 1
  category: 61
  members: true
  max_stack_size: 1
# Separatist Scientist's Breather
- guid: 220024
  name_id: 1408
  description_id: 14
  icon_set_id: 1087
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_DrNuvoVindiBreather.adr
  texture_alias: DrNuvoVindi
  item_type: 1
  category: 60
  members: true
  max_stack_size: 1
# Separatist Scientist's Gloves
- guid: 220025
  name_id: 1380
  description_id: 14
  icon_set_id: 1086
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_DrNuvoVindiGloves.adr
  texture_alias: DrNuvoVindi
  item_type: 1
  category: 62
  members: true
  max_stack_size: 1
# Separatist Scientist's Boots
- guid: 220026
  name_id: 1346
  description_id: 14
  icon_set_id: 1085
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_DrNuvoVindiBoots.adr
  texture_alias: DrNuvoVindi
  item_type: 1
  category: 63
  members: true
  max_stack_size: 1
# Lok Durd's Robes
- guid: 220027
  name_id: 361
  description_id: 14
  icon_set_id: 101
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_LokDurdUniform.adr
  texture_alias: LokDurd
  item_type: 1
  category: 61
  members: true
  max_stack_size: 1
# Lok Durd's Fancy Hat
- guid: 220028
  name_id: 363
  description_id: 14
  icon_set_id: 201
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_LokDurdHat.adr
  texture_alias: LokDurd
  item_type: 1
  category: 60
  members: true
  max_stack_size: 1
# Lok Durd's Boots
- guid: 220029
  name_id: 360
  description_id: 14
  icon_set_id: 143
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_LokDurdBoots.adr
  texture_alias: LokDurd
  item_type: 1
  category: 63
  members: true
  max_stack_size: 1
# Mina Bonteri's Suit
- guid: 220030
  name_id: 1923
  description_id: 14
  icon_set_id: 1452
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_MinaBonteriSuit.adr
  texture_alias: MinaBonteri
  item_type: 1
  category: 61
  members: true
  max_stack_size: 1
# Mina Bonteri's Boots
- guid: 220031
  name_id: 1925
  description_id: 14
  icon_set_id: 1453
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_MinaBonteriBoots.adr
  texture_alias: MinaBonteri
  item_type: 1
  category: 63
  members: true
  max_stack_size: 1
# Zabrak Sith Robes
- guid: 220032
  name_id: 14780
  description_id: 14
  icon_set_id: 461
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_DarthMaulTunic.adr
  texture_alias: DarthMaul
  item_type: 1
  category: 61
  members: true
  max_stack_size: 1
# Zabrak Sith Gloves
- guid: 220033
  name_id: 956
  description_id: 14
  icon_set_id: 463
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_KyleKatarnGloves.adr
  texture_alias: DarthMaul
  item_type: 1
  category: 62
  members: true
  max_stack_size: 1
# Zabrak Sith Boots
- guid: 220034
  name_id: 950
  description_id: 14
  icon_set_id: 462
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_WideBoots.adr
  texture_alias: DarthMaul
  item_type: 1
  category: 63
  members: true
  max_stack_size: 1
# Asajj Ventress' Battle Suit
- guid: 220035
  name_id: 138
  description_id: 14
  icon_set_id: 81
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_AsajjVentressSuit.adr
  texture_alias: AsajjVentress
  item_type: 1
  category: 61
  members: true
  max_stack_size: 1
# Asajj Ventress' Wraps
- guid: 220036
  name_id: 140
  description_id: 14
  icon_set_id: 118
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_AsajjVentressShoes.adr
  texture_alias: AsajjVentress
  item_type: 1
  category: 63
  members: true
  max_stack_size: 1
# Savage Opress' Armor
- guid: 220037
  name_id: 32973
  description_id: 14
  icon_set_id: 1605
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SavageOpressArmor.adr
  texture_alias: Opress
  item_type: 1
  category: 61
  max_stack_size: 1
# Savage Opress' Cuffs
- guid: 220038
  name_id: 32972
  description_id: 14
  icon_set_id: 1607
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_SavageOpressCuffs.adr
  texture_alias: Opress
  item_type: 1
  category: 62
  max_stack_size: 1
# Savage Opress' Boots
- guid: 220039
  name_id: 32974
  description_id: 14
  icon_set_id: 1606
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_SavageOpressBoots.adr
  texture_alias: Opress
  item_type: 1
  category: 63
  max_stack_size: 1
# Darth Sidious' Robes
- guid: 220040
  name_id: 1323
  description_id: 14
  icon_set_id: 1082
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SidiousRobe.adr
  texture_alias: Dark
  item_type: 1
  category: 61
  max_stack_size: 1
# Darth Sidious' Hood
- guid: 220041
  name_id: 1418
  description_id: 14
  icon_set_id: 1083
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_SidiousHood.adr
  texture_alias: Dark
  item_type: 1
  category: 60
  max_stack_size: 1
# Sith Warrior Robe
- guid: 220042
  name_id: 52793
  description_id: 14
  icon_set_id: 3114
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SithAffiliationSuit.adr
  texture_alias: SithAffiliation
  item_type: 1
  category: 61
  max_stack_size: 1
# Sith Warrior Mask
- guid: 220043
  name_id: 52796
  description_id: 14
  icon_set_id: 3117
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_SithAffiliationMask.adr
  texture_alias: SithAffiliation
  item_type: 1
  category: 60
  max_stack_size: 1
# Sith Warrior Gauntlets
- guid: 220044
  name_id: 52794
  description_id: 14
  icon_set_id: 3116
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_DarkForceGlovesPhase03.adr
  texture_alias: SithAffiliation
  item_type: 1
  category: 62
  max_stack_size: 1
# Sith Warrior Boots
- guid: 220045
  name_id: 52795
  description_id: 14
  icon_set_id: 3115
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_DarkForceBootsPhase01.adr
  texture_alias: SithAffiliation
  item_type: 1
  category: 63
  max_stack_size: 1
# Sith Infiltrator Armor
- guid: 220046
  name_id: 2685
  description_id: 14
  icon_set_id: 2852
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_DarkForceArmorPhase01.adr
  texture_alias: Phase01
  item_type: 1
  category: 61
  max_stack_size: 1
# Sith Infiltrator Helm
- guid: 220047
  name_id: 2683
  description_id: 14
  icon_set_id: 2850
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_DarkForceMaskPhase01.adr
  texture_alias: Phase01
  item_type: 1
  category: 60
  max_stack_size: 1
# Sith Infiltrator Gauntlets
- guid: 220048
  name_id: 2684
  description_id: 14
  icon_set_id: 2851
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_DarkForceGlovesPhase01.adr
  texture_alias: Phase01
  item_type: 1
  category: 62
  max_stack_size: 1
# Sith Infiltrator Greaves
- guid: 220049
  name_id: 2686
  description_id: 14
  icon_set_id: 2853
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_DarkForceBootsPhase01.adr
  texture_alias: Phase01
  item_type: 1
  category: 63
  max_stack_size: 1
# Sith Marauder Robe
- guid: 220050
  name_id: 43703
  description_id: 14
  icon_set_id: 1880
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_DarkForceArmorPhase03.adr
  texture_alias: Phase03
  item_type: 1
  category: 61
  max_stack_size: 1
# Sith Marauder Helm
- guid: 220051
  name_id: 43701
  description_id: 14
  icon_set_id: 1883
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_Human_<gender>_Head_DarkForceMaskPhase03.adr
  texture_alias: Phase03
  item_type: 1
  category: 60
  max_stack_size: 1
# Sith Marauder Vambraces
- guid: 220052
  name_id: 43702
  description_id: 14
  icon_set_id: 1882
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_DarkForceGlovesPhase03.adr
  texture_alias: Phase03
  item_type: 1
  category: 62
  max_stack_size: 1
# Sith Marauder Greaves
- guid: 220053
  name_id: 43704
  description_id: 14
  icon_set_id: 1881
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_DarkForceBootsPhase03.adr
  texture_alias: Phase03
  item_type: 1
  category: 63
  max_stack_size: 1
# Sith Inquisitor Suit
- guid: 220054
  name_id: 4926
  description_id: 14
  icon_set_id: 1876
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_DarkForceArmorPhase02.adr
  texture_alias: Phase02
  item_type: 1
  category: 61
  max_stack_size: 1
# Sith Inquisitor Helm
- guid: 220055
  name_id: 4924
  description_id: 14
  icon_set_id: 1879
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_Human_<gender>_Head_DarkForceMaskPhase02.adr
  texture_alias: Phase02
  item_type: 1
  category: 60
  max_stack_size: 1
# Sith Inquisitor Gauntlets
- guid: 220056
  name_id: 4925
  description_id: 14
  icon_set_id: 1878
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_DarkForceGlovesPhase02.adr
  texture_alias: Phase02
  item_type: 1
  category: 62
  max_stack_size: 1
# Sith Inquisitor Boots
- guid: 220057
  name_id: 4927
  description_id: 14
  icon_set_id: 1877
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_DarkForceBootsPhase02.adr
  texture_alias: Phase02
  item_type: 1
  category: 63
  max_stack_size: 1
# Crimson Kofun Armor
- guid: 220058
  name_id: 53972
  description_id: 14
  icon_set_id: 3272
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SamuraiJediV2Armor.adr
  texture_alias: SamuraiSith
  item_type: 1
  category: 61
  max_stack_size: 1
# Crimson Kofun Helmet
- guid: 220059
  name_id: 53970
  description_id: 14
  icon_set_id: 3270
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_Human_<gender>_Head_SamuraiJediV2Mask.adr
  texture_alias: SamuraiSith
  item_type: 1
  category: 60
  max_stack_size: 1
# Crimson Kofun Arm Wraps
- guid: 220060
  name_id: 53971
  description_id: 14
  icon_set_id: 3271
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_<race>_<gender>_Hands_SamuraiJediV2Gloves.adr
  texture_alias: SamuraiSith
  item_type: 1
  category: 62
  max_stack_size: 1
# Crimson Kofun Leg Wraps
- guid: 220061
  name_id: 53973
  description_id: 14
  icon_set_id: 3273
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_<race>_<gender>_Feet_SamuraiJediV2Wraps.adr
  texture_alias: SamuraiSith
  item_type: 1
  category: 63
  max_stack_size: 1
# Dark Sith Cowl
- guid: 220062
  name_id: 4979
  description_id: 14
  icon_set_id: 3015
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_RebornHood.adr
  texture_alias: RebornRedTrim
  item_type: 1
  category: 60
  max_stack_size: 1
# Maroon Sith Cowl
- guid: 220063
  name_id: 4978
  description_id: 14
  icon_set_id: 3016
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_RebornHood.adr
  texture_alias: RebornRedStripes
  item_type: 1
  category: 60
  max_stack_size: 1
# Red Sith Cowl
- guid: 220064
  name_id: 4977
  description_id: 14
  icon_set_id: 3017
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_RebornHood.adr
  texture_alias: RebornBlack
  item_type: 1
  category: 60
  max_stack_size: 1
# Crimson Prowler Suit
- guid: 220065
  name_id: 60196
  description_id: 14
  icon_set_id: 3717
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SparkingCrystalSuit.adr
  texture_alias: DarkKnight
  item_type: 1
  category: 61
  max_stack_size: 1
# Crimson Prowler Hood
- guid: 220066
  name_id: 60194
  description_id: 14
  icon_set_id: 3720
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_<race>_<gender>_Head_SparkingCrystalHood.adr
  texture_alias: DarkKnight
  item_type: 1
  category: 60
  max_stack_size: 1
# Crimson Prowler Gloves
- guid: 220067
  name_id: 60195
  description_id: 14
  icon_set_id: 3719
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_CloneSnowGloves.adr
  texture_alias: DarkKnight
  item_type: 1
  category: 62
  max_stack_size: 1
# Crimson Prowler Boots
- guid: 220068
  name_id: 60197
  description_id: 14
  icon_set_id: 3718
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_SparkingCrystalBoots.adr
  texture_alias: DarkKnight
  item_type: 1
  category: 63
  max_stack_size: 1
