---
# Luke Skywalker's Robes
- guid: 230000
  name_id: 924
  description_id: 14
  icon_set_id: 480
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SimpleGiPouches.adr
  texture_alias: LukeTatooine
  item_type: 1
  category: 61
  max_stack_size: 1
# Luke Skywalker's Boots
- guid: 230001
  name_id: 365
  description_id: 14
  icon_set_id: 122
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_Boots.adr
  texture_alias: LukeTatooine
  item_type: 1
  category: 63
  max_stack_size: 1
# Kyle Katarn's Boots
- guid: 230002
  name_id: 206
  description_id: 14
  icon_set_id: 142
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_KyleKatarnBoots.adr
  texture_alias: KyleKatarn
  item_type: 1
  category: 63
  max_stack_size: 1
# Kyle Katarn's Uniform
- guid: 230003
  name_id: 204
  description_id: 14
  icon_set_id: 673
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_KyleKatarnSuit.adr
  texture_alias: KyleKatarnDark
  item_type: 1
  category: 61
  max_stack_size: 1
# Kyle Katarn's Gloves
- guid: 230004
  name_id: 202
  description_id: 14
  icon_set_id: 676
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_KyleKatarnGloves.adr
  texture_alias: KyleKatarnDark
  item_type: 1
  category: 62
  max_stack_size: 1
# Kyle Katarn's Boots
- guid: 230005
  name_id: 206
  description_id: 14
  icon_set_id: 680
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_KyleKatarnBoots.adr
  texture_alias: KyleKatarnDark
  item_type: 1
  category: 63
  max_stack_size: 1
# Lando Calrissian's Suit
- guid: 230006
  name_id: 1462
  description_id: 14
  icon_set_id: 673
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_LandoSuit.adr
  texture_alias: LandoArmor
  item_type: 1
  category: 61
  max_stack_size: 1
# Lando Calrissian's Shoes
- guid: 230007
  name_id: 1472
  description_id: 14
  icon_set_id: 680
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_LandoShoes.adr
  texture_alias: LandoArmor
  item_type: 1
  category: 63
  max_stack_size: 1
# Tamtel Skreej's Armor
- guid: 230008
  name_id: 930
  description_id: 14
  icon_set_id: 495
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_SkiffGuardArmor.adr
  texture_alias: TamtelSkreej
  item_type: 1
  category: 61
  max_stack_size: 1
# Tamtel Skreej's Helm
- guid: 230009
  name_id: 928
  description_id: 14
  icon_set_id: 497
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_Human_<gender>_Head_TuskHelm.adr
  texture_alias: TamtelSkreej
  item_type: 1
  category: 60
  max_stack_size: 1
# Tamtel Skreej's Boots
- guid: 230010
  name_id: 932
  description_id: 14
  icon_set_id: 496
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_LooseBoots.adr
  texture_alias: TamtelSkreej
  item_type: 1
  category: 63
  max_stack_size: 1
# Mara Jade's Battle Suit
- guid: 230011
  name_id: 216
  description_id: 14
  icon_set_id: 104
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_MaraJadeSuit.adr
  texture_alias: MaraJade
  item_type: 1
  category: 61
  max_stack_size: 1
# Mara Jade's Gloves
- guid: 230012
  name_id: 214
  description_id: 14
  icon_set_id: 174
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_MaraJadeGloves.adr
  texture_alias: MaraJade
  item_type: 1
  category: 62
  max_stack_size: 1
# Mara Jade's Boots
- guid: 230013
  name_id: 218
  description_id: 14
  icon_set_id: 147
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_MaraJadeBoots.adr
  texture_alias: MaraJade
  item_type: 1
  category: 63
  max_stack_size: 1
# Imperial Royal Guard Armor
- guid: 230014
  name_id: 1650
  description_id: 14
  icon_set_id: 673
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_ImperialRoyalGuardSuit.adr
  texture_alias: RoyalGuard
  item_type: 1
  category: 61
  max_stack_size: 1
# Imperial Royal Guard Helmet
- guid: 230015
  name_id: 1646
  description_id: 14
  icon_set_id: 677
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_Human_<gender>_Head_ImperialRoyalGuardHelmWrap.adr
  texture_alias: RoyalGuard
  item_type: 1
  category: 60
  max_stack_size: 1
# Imperial Royal Guard Gloves
- guid: 230016
  name_id: 1648
  description_id: 14
  icon_set_id: 676
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_ShortGloves.adr
  texture_alias: RoyalGuard
  item_type: 1
  category: 62
  max_stack_size: 1
# Imperial Royal Guard Boots
- guid: 230017
  name_id: 1652
  description_id: 14
  icon_set_id: 680
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_HeeledRidgeBoots.adr
  texture_alias: RoyalGuard
  item_type: 1
  category: 63
  max_stack_size: 1
# Dash Rendar's Suit
- guid: 230018
  name_id: 1565
  description_id: 14
  icon_set_id: 673
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_DashRendarSuit.adr
  texture_alias: DashRendar
  item_type: 1
  category: 61
  max_stack_size: 1
# Dash Rendar's Gloves
- guid: 230019
  name_id: 1563
  description_id: 14
  icon_set_id: 676
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_DashRendarGloves.adr
  texture_alias: DashRendar
  item_type: 1
  category: 62
  max_stack_size: 1
# Dash Rendar's Boots
- guid: 230020
  name_id: 1567
  description_id: 14
  icon_set_id: 680
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_Boots.adr
  texture_alias: DashRendar
  item_type: 1
  category: 63
  max_stack_size: 1
# Han Solo's Outfit
- guid: 230021
  name_id: 302
  description_id: 14
  icon_set_id: 673
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_HanSoloSuit.adr
  texture_alias: HanSoloJacket
  item_type: 1
  category: 61
  max_stack_size: 1
# Han Solo's Boots
- guid: 230022
  name_id: 304
  description_id: 14
  icon_set_id: 680
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_HanSoloBoots.adr
  texture_alias: HanSoloJacket
  item_type: 1
  category: 63
  max_stack_size: 1
# Rebel Pilot Jumpsuit
- guid: 230023
  name_id: 240
  description_id: 14
  icon_set_id: 108
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_RebelPilotSuit.adr
  texture_alias: RebelPilot
  item_type: 1
  category: 61
  max_stack_size: 1
# Rebel Pilot Helmet
- guid: 230024
  name_id: 236
  description_id: 14
  icon_set_id: 205
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_Human_<gender>_Head_RebelPilotHelm.adr
  texture_alias: RebelPilot
  item_type: 1
  category: 60
  max_stack_size: 1
# Rebel Pilot Gloves
- guid: 230025
  name_id: 238
  description_id: 14
  icon_set_id: 177
  item_class: -1
  slot: !Equipment Hands
  model_name: Wear_Human_<gender>_Hands_RebelPilotGloves.adr
  texture_alias: Black
  item_type: 1
  category: 62
  max_stack_size: 1
# Rebel Pilot Boots
- guid: 230026
  name_id: 242
  description_id: 14
  icon_set_id: 150
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_RebelPilotBoots.adr
  texture_alias: Black
  item_type: 1
  category: 63
  max_stack_size: 1
# Rebel Pilot Jumpsuit
- guid: 230027
  name_id: 240
  description_id: 14
  icon_set_id: 673
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_RebelPilotSuit.adr
  texture_alias: Green
  item_type: 1
  category: 61
  max_stack_size: 1
# Rebel Pilot Helmet
- guid: 230028
  name_id: 236
  description_id: 14
  icon_set_id: 677
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_Human_<gender>_Head_RebelPilotHelm.adr
  texture_alias: Green
  item_type: 1
  category: 60
  max_stack_size: 1
# Rebel Pilot Jumpsuit
- guid: 230029
  name_id: 240
  description_id: 14
  icon_set_id: 673
  item_class: -1
  slot: !Equipment Body
  model_name: Wear_Human_<gender>_Body_RebelPilotSuit.adr
  texture_alias: Red
  item_type: 1
  category: 61
  max_stack_size: 1
# Rebel Pilot Helmet
- guid: 230030
  name_id: 236
  description_id: 14
  icon_set_id: 677
  item_class: -1
  slot: !Equipment Head
  model_name: Wear_Human_<gender>_Head_RebelPilotHelm.adr
  texture_alias: Red
  item_type: 1
  category: 60
  max_stack_size: 1
# Unknown boots
- guid: 230031
  description_id: 14
  icon_set_id: 680
  item_class: -1
  slot: !Equipment Feet
  model_name: Wear_Human_<gender>_Feet_FrontAngledBoots.adr
  texture_alias: BrownIndigo
  item_type: 1
  category: 63
  max_stack_size: 1
