---
# Unknown boots
- guid: 40158
  name_id: 0
  description_id: 14
  icon_set_id: 680
  tint: 0
  unknown6: 0
  unknown7: 0
  cost: 0
  item_class: -1
  required_battle_class: 0
  slot: !Equipment Feet
  disable_trade: false
  disable_sale: false
  model_name: Wear_Human_<gender>_Feet_FrontAngledBoots.adr
  texture_alias: BrownIndigo
  required_gender: 0
  item_type: 1
  category: 63
  members: false
  non_minigame: false
  weapon_trail_effect: 0
  composite_effect: 0
  power_rating: 0
  min_battle_class_level: 0
  rarity: 0
  activatable_ability_id: 0
  passive_ability_id: 0
  single_use: false
  max_stack_size: 1
  is_tintable: false
  tint_alias: ''
  disable_preview: false
  unknown33: false
  race_set_id: 0
  unknown35: false
  unknown36: 0
  unknown37: 0
  customization_slot: None
  customization_id: 0
  unknown40: 0
  stats: []
  abilities: []
