---
umbara:
  ambient_npcs:
    holo_table:
      name_id: 32914
      model_id: 1603
      pos:
        x: 74.2301
        y: 1.9294561
        z: 36.314392
        w: 1
      rot:
        x: 0.5
        y: 0
        z: 0.85
        w: 0
      cursor: 54
      show_name: false
      interact_radius: 3.3
      move_to_interact_offset: 3.2
      interact_popup_radius: 7
      one_shot_interaction:
        script: OpenGalaxyMap
        duration_millis: 1
    fighter:
      name_id: 32914
      terrain_object_id: 1319570319
      pos:
        x: 87
        y: 3
        z: 101
        w: 1
      rot:
        x: 0
        y: 0
        z: 0
        w: 0
      name_offset_x: -0.5
      cursor: 0
      show_name: false
      notification_icon: 37
      hover_description: UseName
      one_shot_interaction:
        script: OpenGalaxyMap
        duration_millis: 1
    gunship:
      name_id: 32914
      model_id: 2133
      scale: 0.55
      pos:
        x: 156.5
        y: 0.9885109
        z: 91
        w: 1
      rot:
        x: 1
        y: 0
        z: 0.13
        w: 0
      name_offset_x: 3
      name_offset_y: 0
      name_offset_z: 5
      cursor: 54
      interact_radius: 15
      move_to_interact_offset: 14
      show_name: false
      notification_icon: 46
      hover_description: UseName
      one_shot_interaction:
        script: OpenGalaxyMap
        duration_millis: 1
