name: 'Build and Test'
on:
  push:
  pull_request:
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  run-tests:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
      - name: Run tests
        run: cargo test
      - name: Check configuration
        run: cargo run -- --validate
      - name: Lint
        run: cargo clippy -- -Dwarnings -A unused -A clippy::too_many_arguments
      - name: Check style (Rust)
        run: cargo fmt --all --check
      - name: Check style (YAML)
        run: yamllint --strict config/
  run-tests-asset-serialize:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
      - name: Change directory
        run: cd crates/asset_serialize
      - name: Run tests
        run: cargo test
      - name: Lint
        run: cargo clippy -- -Dwarnings -A unused -A clippy::too_many_arguments
      - name: Check style (Rust)
        run: cargo fmt --all --check
  run-tests-packet-serialize:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
      - name: Change directory
        run: cd crates/packet_serialize
      - name: Run tests
        run: cargo test
      - name: Lint
        run: cargo clippy -- -Dwarnings -A unused -A clippy::too_many_arguments
      - name: Check style (Rust)
        run: cargo fmt --all --check
  run-tests-packet-serialize-derive:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
      - name: Change directory
        run: cd crates/packet_serialize_derive
      - name: Run tests
        run: cargo test
      - name: Lint
        run: cargo clippy -- -Dwarnings -A unused -A clippy::too_many_arguments
      - name: Check style (Rust)
        run: cargo fmt --all --check
